// Lecture export utilities: PDF, DOCX, PPTX
import jsPDF from 'jspdf';

function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s+/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`{1,3}(.*?)`{1,3}/gs, '$1')
    .replace(/\[(.*?)\]\(.*?\)/g, '$1')
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/^\d+\.\s+/gm, '')
    .replace(/\\\((.*?)\\\)/gs, '$1')
    .replace(/\$\$(.*?)\$\$/gs, '$1')
    .replace(/\$(.*?)\$/g, '$1')
    .trim();
}

export async function exportAsPDF(title: string, content: string): Promise<void> {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  const titleLines = pdf.splitTextToSize(title, maxWidth);
  pdf.text(titleLines, margin, y);
  y += titleLines.length * 8 + 6;

  // Divider
  pdf.setDrawColor(100, 100, 255);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Content
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  const clean = stripMarkdown(content);
  const paragraphs = clean.split('\n').filter(Boolean);

  for (const para of paragraphs) {
    const lines = pdf.splitTextToSize(para, maxWidth);
    if (y + lines.length * 6 > pdf.internal.pageSize.getHeight() - margin) {
      pdf.addPage();
      y = margin;
    }
    pdf.text(lines, margin, y);
    y += lines.length * 6 + 3;
  }

  pdf.save(`${title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
}

export async function exportAsDOCX(title: string, content: string): Promise<void> {
  // Use docx library dynamically
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx');

  const clean = stripMarkdown(content);
  const lines = clean.split('\n').filter(Boolean);

  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
    }),
    ...lines.map(line =>
      new Paragraph({
        children: [new TextRun({ text: line, size: 24 })],
        spacing: { after: 100 },
      })
    ),
  ];

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, '_')}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function exportAsPPTX(title: string, content: string, images?: string[]): Promise<void> {
  const pptxgenjs = await import('pptxgenjs');
  const PptxGenJS = pptxgenjs.default;
  const pptx = new PptxGenJS();

  pptx.layout = 'LAYOUT_WIDE';

  const clean = stripMarkdown(content);
  const paragraphs = clean.split('\n\n').filter(Boolean);

  // Brand colors
  const primaryColor = '6366F1';
  const darkBg = '1E1B4B';
  const lightText = 'E0E7FF';
  const accentColor = '818CF8';

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: darkBg };
  // Accent bar
  titleSlide.addShape('rect' as any, {
    x: 0, y: 0, w: 0.15, h: '100%',
    fill: { type: 'solid', color: primaryColor },
  });
  // Decorative circle
  titleSlide.addShape('ellipse' as any, {
    x: 9.5, y: -1, w: 4, h: 4,
    fill: { type: 'solid', color: primaryColor },
  });
  titleSlide.addText(title, {
    x: 0.8, y: 1.2, w: 8, h: 2,
    fontSize: 40, bold: true, color: 'FFFFFF', fontFace: 'Arial',
  });
  titleSlide.addText('Generated by Study Bright AI', {
    x: 0.8, y: 3.5, w: 8, h: 0.5,
    fontSize: 14, color: lightText, fontFace: 'Arial',
  });
  // Divider line
  titleSlide.addShape('rect' as any, {
    x: 0.8, y: 4.2, w: 3, h: 0.04,
    fill: { type: 'solid', color: accentColor },
  });

  // Content slides - professional layout
  const chunkSize = 2;
  for (let i = 0; i < paragraphs.length; i += chunkSize) {
    const slide = pptx.addSlide();
    slide.background = { color: 'FFFFFF' };
    // Top accent bar
    slide.addShape('rect' as any, {
      x: 0, y: 0, w: '100%', h: 0.06,
      fill: { type: 'solid', color: primaryColor },
    });
    // Left accent
    slide.addShape('rect' as any, {
      x: 0, y: 0, w: 0.08, h: '100%',
      fill: { type: 'solid', color: primaryColor },
    });

    const slideNum = Math.floor(i / chunkSize) + 1;
    slide.addText(`Section ${slideNum}`, {
      x: 0.6, y: 0.3, w: '85%', h: 0.6,
      fontSize: 22, bold: true, color: primaryColor, fontFace: 'Arial',
    });
    // Divider
    slide.addShape('rect' as any, {
      x: 0.6, y: 0.9, w: 2, h: 0.03,
      fill: { type: 'solid', color: accentColor },
    });

    const chunk = paragraphs.slice(i, i + chunkSize).join('\n\n');
    slide.addText(chunk, {
      x: 0.6, y: 1.2, w: '88%', h: 5.5,
      fontSize: 15, color: '374151', fontFace: 'Arial',
      align: 'left', valign: 'top', wrap: true,
      lineSpacingMultiple: 1.3,
    });

    // Footer
    slide.addText(`Study Bright AI  •  ${title}`, {
      x: 0.6, y: 7.0, w: '80%', h: 0.3,
      fontSize: 9, color: '9CA3AF', fontFace: 'Arial',
    });
  }

  // Image slides
  if (images && images.length > 0) {
    const imgSlide = pptx.addSlide();
    imgSlide.background = { color: darkBg };
    imgSlide.addShape('rect' as any, {
      x: 0, y: 0, w: '100%', h: 0.06,
      fill: { type: 'solid', color: primaryColor },
    });
    imgSlide.addText('Visual References', {
      x: 0.6, y: 0.2, w: '85%', h: 0.6,
      fontSize: 22, bold: true, color: 'FFFFFF', fontFace: 'Arial',
    });

    const imgWidth = images.length === 1 ? 8 : images.length === 2 ? 5.5 : 3.8;
    for (let i = 0; i < Math.min(images.length, 3); i++) {
      const base64 = await fetchImageAsBase64(images[i]);
      if (base64) {
        const xPos = images.length === 1 ? 2 : images.length === 2 ? (i * 6 + 0.5) : (i * 4.2 + 0.5);
        imgSlide.addImage({
          data: base64,
          x: xPos, y: 1.2, w: imgWidth, h: 4.5,
          rounding: true,
        });
      }
    }
  }

  await pptx.writeFile({ fileName: `${title.replace(/[^a-z0-9]/gi, '_')}.pptx` });
}
