
-- ============================================
-- MODERATOR SYSTEM: Full Database Schema
-- ============================================

-- 1. Moderator invite codes (generated by ministry)
CREATE TABLE public.moderator_invite_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL,
  used boolean NOT NULL DEFAULT false,
  used_by uuid,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(code)
);
ALTER TABLE public.moderator_invite_codes ENABLE ROW LEVEL SECURITY;

-- Only super admin (ministry) can manage these
CREATE POLICY "Super admin can manage moderator codes" ON public.moderator_invite_codes
  FOR ALL USING (lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text)
  WITH CHECK (lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text);

-- 2. Moderator requests (pending approval by ministry)
CREATE TABLE public.moderator_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code_id uuid REFERENCES public.moderator_invite_codes(id) NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  user_id uuid,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.moderator_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super admin can manage moderator requests" ON public.moderator_requests
  FOR ALL USING (lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text)
  WITH CHECK (lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text);

CREATE POLICY "Users can view own moderator request by email" ON public.moderator_requests
  FOR SELECT USING (lower(email) = lower((auth.jwt() ->> 'email'::text)));

-- Allow anon to insert (signup before auth)
CREATE POLICY "Anyone can submit moderator request" ON public.moderator_requests
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- 3. Content flags (AI-detected or manually reported)
CREATE TABLE public.content_flags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_type text NOT NULL, -- 'chat_message', 'course_material', 'assignment'
  content_id text, -- reference ID
  content_text text NOT NULL, -- the flagged content
  user_id uuid NOT NULL, -- who created the content
  school_id uuid REFERENCES public.schools(id),
  severity text NOT NULL DEFAULT 'medium', -- 'low', 'medium', 'high', 'critical'
  reason text, -- AI explanation
  status text NOT NULL DEFAULT 'pending', -- 'pending', 'reviewed', 'dismissed'
  reviewed_by uuid, -- moderator who reviewed
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.content_flags ENABLE ROW LEVEL SECURITY;

-- Moderators can view all flags (moderator = user_type 'moderator' in profiles)
CREATE POLICY "Moderators can view all flags" ON public.content_flags
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND user_type = 'moderator' AND is_active = true)
    OR lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text
  );

CREATE POLICY "Moderators can update flags" ON public.content_flags
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND user_type = 'moderator' AND is_active = true)
    OR lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text
  );

-- System can insert flags (via edge function with service role)
CREATE POLICY "System can insert flags" ON public.content_flags
  FOR INSERT WITH CHECK (true);

-- 4. Moderation actions (warn, ban, terminate)
CREATE TABLE public.moderation_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_id uuid REFERENCES public.content_flags(id),
  target_user_id uuid NOT NULL, -- the user being actioned
  moderator_id uuid NOT NULL, -- the moderator taking action
  action_type text NOT NULL, -- 'warning', 'temp_ban', 'terminate'
  message text, -- warning message or reason
  school_id uuid REFERENCES public.schools(id),
  expires_at timestamptz, -- for temp_ban (24h)
  is_active boolean NOT NULL DEFAULT true,
  appeal_status text DEFAULT 'none', -- 'none', 'appealed', 'upheld', 'overturned'
  appealed_by uuid, -- school admin who appealed
  appeal_reason text,
  appeal_resolved_by uuid, -- moderator/ministry/super admin who resolved
  appeal_resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.moderation_actions ENABLE ROW LEVEL SECURITY;

-- Moderators can manage actions
CREATE POLICY "Moderators can manage actions" ON public.moderation_actions
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND user_type = 'moderator' AND is_active = true)
    OR lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND user_type = 'moderator' AND is_active = true)
    OR lower((auth.jwt() ->> 'email'::text)) = 'malekismail487@gmail.com'::text
  );

-- School admins can view actions for their school
CREATE POLICY "School admins can view school actions" ON public.moderation_actions
  FOR SELECT USING (
    school_id IS NOT NULL AND is_school_admin_of(auth.uid(), school_id)
  );

-- School admins can update appeal fields
CREATE POLICY "School admins can appeal actions" ON public.moderation_actions
  FOR UPDATE USING (
    school_id IS NOT NULL AND is_school_admin_of(auth.uid(), school_id)
  );

-- Target users can view their own actions
CREATE POLICY "Users can view own actions" ON public.moderation_actions
  FOR SELECT USING (target_user_id = auth.uid());

-- ============================================
-- RPC Functions
-- ============================================

-- Generate moderator invite code (ministry only)
CREATE OR REPLACE FUNCTION public.generate_moderator_invite_code()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_caller_email text;
  v_code text;
  v_expires_at timestamptz;
BEGIN
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();
  IF v_caller_email != 'malekismail487@gmail.com' THEN
    RETURN json_build_object('success', false, 'error', 'Unauthorized');
  END IF;

  v_expires_at := now() + interval '48 hours';

  FOR i IN 1..5 LOOP
    v_code := 'MOD-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8));
    BEGIN
      INSERT INTO moderator_invite_codes (code, expires_at)
      VALUES (v_code, v_expires_at);
      RETURN json_build_object('success', true, 'code', v_code, 'expires_at', v_expires_at);
    EXCEPTION WHEN unique_violation THEN
      CONTINUE;
    END;
  END LOOP;

  RETURN json_build_object('success', false, 'error', 'Failed to generate unique code');
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.generate_moderator_invite_code() TO authenticated;

-- Signup as moderator (called before auth, so needs anon access)
CREATE OR REPLACE FUNCTION public.signup_as_moderator(p_email text, p_invite_code text, p_full_name text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_code_record RECORD;
  v_request_id uuid;
BEGIN
  SELECT * INTO v_code_record FROM moderator_invite_codes
  WHERE code = upper(p_invite_code) AND used = false AND expires_at > now();

  IF v_code_record IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Invalid or expired invite code');
  END IF;

  IF EXISTS (SELECT 1 FROM moderator_requests WHERE lower(email) = lower(p_email) AND status = 'pending') THEN
    RETURN json_build_object('success', false, 'error', 'Request already pending');
  END IF;

  INSERT INTO moderator_requests (code_id, name, email, status)
  VALUES (v_code_record.id, p_full_name, lower(p_email), 'pending')
  RETURNING id INTO v_request_id;

  RETURN json_build_object('success', true, 'request_id', v_request_id);
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.signup_as_moderator(text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.signup_as_moderator(text, text, text) TO authenticated;

-- Approve moderator request (ministry only)
CREATE OR REPLACE FUNCTION public.approve_moderator_request(p_request_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_request RECORD;
  v_caller_email text;
  v_user_id uuid;
BEGIN
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();
  IF v_caller_email != 'malekismail487@gmail.com' THEN
    RETURN json_build_object('success', false, 'error', 'Unauthorized');
  END IF;

  SELECT * INTO v_request FROM moderator_requests WHERE id = p_request_id AND status = 'pending';
  IF v_request IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Request not found');
  END IF;

  v_user_id := v_request.user_id;

  -- Create profile
  IF v_user_id IS NOT NULL THEN
    INSERT INTO profiles (id, full_name, email, user_type, status, is_active)
    VALUES (v_user_id, v_request.name, v_request.email, 'moderator', 'approved', true)
    ON CONFLICT (id) DO UPDATE SET
      full_name = EXCLUDED.full_name,
      user_type = 'moderator',
      status = 'approved',
      is_active = true;
  ELSE
    INSERT INTO profiles (id, full_name, email, user_type, status, is_active)
    VALUES (gen_random_uuid(), v_request.name, v_request.email, 'moderator', 'approved', true);
  END IF;

  UPDATE moderator_requests SET status = 'approved', updated_at = now() WHERE id = p_request_id;
  UPDATE moderator_invite_codes SET used = true, used_by = v_user_id WHERE id = v_request.code_id;

  RETURN json_build_object('success', true);
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.approve_moderator_request(uuid) TO authenticated;

-- Deny moderator request
CREATE OR REPLACE FUNCTION public.deny_moderator_request(p_request_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_caller_email text;
BEGIN
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();
  IF v_caller_email != 'malekismail487@gmail.com' THEN
    RETURN json_build_object('success', false, 'error', 'Unauthorized');
  END IF;

  UPDATE moderator_requests SET status = 'rejected', updated_at = now() WHERE id = p_request_id AND status = 'pending';

  RETURN json_build_object('success', true);
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.deny_moderator_request(uuid) TO authenticated;

-- Link moderator profile after signup (similar to link_profile_after_signup)
CREATE OR REPLACE FUNCTION public.link_moderator_after_signup(p_user_id uuid, p_email text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_request RECORD;
  v_old_profile_id uuid;
BEGIN
  -- Update moderator_requests with user_id
  UPDATE moderator_requests SET user_id = p_user_id WHERE lower(email) = lower(p_email) AND user_id IS NULL;

  -- Check if there's an approved moderator profile to link
  SELECT id INTO v_old_profile_id FROM profiles
  WHERE lower(email) = lower(p_email) AND user_type = 'moderator' AND status = 'approved' AND id != p_user_id
  LIMIT 1;

  IF v_old_profile_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = p_user_id) THEN
      UPDATE profiles SET id = p_user_id, updated_at = now() WHERE id = v_old_profile_id;
      RETURN json_build_object('success', true, 'linked', true);
    END IF;
  END IF;

  RETURN json_build_object('success', true, 'linked', false);
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.link_moderator_after_signup(uuid, text) TO authenticated;

-- Check if user is a moderator
CREATE OR REPLACE FUNCTION public.is_moderator(user_uuid uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = user_uuid AND user_type = 'moderator' AND is_active = true AND status = 'approved'
  )
$fn$;

GRANT EXECUTE ON FUNCTION public.is_moderator(uuid) TO authenticated;
