/** Exact source refinement, not a replacement of any historical scored-source identity. */
export const NYX_ARC_CORE_REFINEMENT = Object.freeze({
  predecessor: "513845addbe6146a4ad1b08a68176bff1b5f8b24",
  purpose: "MATCH_INFERENCE_CANCELLATION_ARRAY_BOUNDS_AND_OPT_IN_DELIVERY_AND_MEASURED_QUALITY_GUIDANCE",
  historicalScoresComparable: false, acceptanceOracleChanged: false, authorityIncrease: false,
  defaultInferencePolicyChanged: false,
});
const cognitivePath = "src/lib/codelab/cognition/nyxNemotronEngineeringCognition.ts";
const loopPath = "src/lib/codelab/engine/r3BoundedRepairLoop.ts";
const qualityPath = "src/lib/codelab/assurance/engineeringQualityOracle.ts";
const changes: Record<string, readonly (readonly [string, string, number?])[]> = {
  ["src/lib/codelab/model/nvidiaNimProvider.ts"]: [
    ["  readonly state: \"DELIVERED\" | \"WAITING_FOR_CAPACITY\" | \"STOPPED\";\n  readonly notBeforeEpochMs: number | null;\n  readonly authorityRenewed: false;\n}\n\nexport interface NvidiaNimCompletionResult {\n","  readonly state: \"DELIVERED\" | \"WAITING_FOR_CAPACITY\" | \"STOPPED\";\n  readonly notBeforeEpochMs: number | null;\n  readonly authorityRenewed: false;\n  /** Host-owned dispatch budget shared by logical calls and retries, never supplied to the model. */\n  readonly httpAttemptBudget?: {\n    readonly scope: \"HOST_OWNED_RUN_INCLUDING_RETRIES\";\n    readonly limit: number;\n    readonly dispatched: number;\n    readonly remainingAttempts: number;\n    readonly exhausted: boolean;\n    readonly dispatchDenied: boolean;\n    readonly renewed: false;\n  };\n}\n\nexport interface NvidiaNimCompletionResult {\n"],
    ["  readonly category: NvidiaNimProviderFailureCategory | null;\n  readonly retryability: NvidiaNimRetryability | null;\n} {\n  if (reason === \"nvidia_provider_timeout\") return { category: \"PROVIDER_TIMEOUT\", retryability: \"YES\" };\n  if (reason === \"nvidia_provider_cancelled\") return { category: \"PROVIDER_CANCELLED\", retryability: \"NO\" };\n  if (reason === \"nvidia_provider_transport_failure\") return { category: \"PROVIDER_TRANSPORT_ERROR\", retryability: \"UNKNOWN\" };\n","  readonly category: NvidiaNimProviderFailureCategory | null;\n  readonly retryability: NvidiaNimRetryability | null;\n} {\n  if (reason === \"nvidia_http_attempt_budget_exhausted\") return { category: null, retryability: \"NO\" };\n  if (reason === \"nvidia_provider_timeout\") return { category: \"PROVIDER_TIMEOUT\", retryability: \"YES\" };\n  if (reason === \"nvidia_provider_cancelled\") return { category: \"PROVIDER_CANCELLED\", retryability: \"NO\" };\n  if (reason === \"nvidia_provider_transport_failure\") return { category: \"PROVIDER_TRANSPORT_ERROR\", retryability: \"UNKNOWN\" };\n"],
    ["  readonly #config: NvidiaNimProviderConfig;\n  readonly #transport: NvidiaNimTransport | null;\n  readonly #capacity: NvidiaCapacityCoordinator | null;\n\n  private constructor(config: NvidiaNimProviderConfig, transport: NvidiaNimTransport | null) {\n    this.#config = Object.freeze({ ...config, credentialSource: Object.freeze({ ...config.credentialSource }) });\n    this.#transport = transport;\n    this.#capacity = config.authorityMode === \"EXPLICIT_LIVE_NVIDIA_NIM\" ? liveNvidiaCapacity : config.testCapacity ?? null;\n  }\n\n  static create(config: NvidiaNimProviderConfig): NvidiaNimProvider {\n","  readonly #config: NvidiaNimProviderConfig;\n  readonly #transport: NvidiaNimTransport | null;\n  readonly #capacity: NvidiaCapacityCoordinator | null;\n  readonly #httpAttemptBudgets: readonly { readonly limit: number; dispatched: number }[];\n\n  private constructor(config: NvidiaNimProviderConfig, transport: NvidiaNimTransport | null,\n    budgets: readonly { readonly limit: number; dispatched: number }[] = []) {\n    this.#config = Object.freeze({ ...config, credentialSource: Object.freeze({ ...config.credentialSource }) });\n    this.#transport = transport;\n    this.#capacity = config.authorityMode === \"EXPLICIT_LIVE_NVIDIA_NIM\" ? liveNvidiaCapacity : config.testCapacity ?? null;\n    this.#httpAttemptBudgets = Object.freeze([...budgets]);\n  }\n\n  static create(config: NvidiaNimProviderConfig): NvidiaNimProvider {\n"],
    ["    return Object.freeze({ ...NVIDIA_NIM_PROVIDER_STATUS, authorityMode: this.#config.authorityMode, model: this.#config.model });\n  }\n\n  async complete(request: NvidiaNimCompletionRequest): Promise<NvidiaNimCompletionResult> {\n    const requestId = typeof request.requestId === \"string\" && request.requestId.trim() ? request.requestId : \"MALFORMED\";\n    const responseFormat = responseFormatPayload(request.responseFormat);\n","    return Object.freeze({ ...NVIDIA_NIM_PROVIDER_STATUS, authorityMode: this.#config.authorityMode, model: this.#config.model });\n  }\n\n  /** A trusted host creates one scope per task/run. Nested scopes cannot refill their ancestor. */\n  withHttpAttemptBudget(limit: number): NvidiaNimProvider {\n    if (!Number.isSafeInteger(limit) || limit < 1) throw new Error(\"nvidia_http_attempt_budget_invalid\");\n    return new NvidiaNimProvider(this.#config, this.#transport, [...this.#httpAttemptBudgets, { limit, dispatched: 0 }]);\n  }\n\n  #remainingHttpAttempts(): number {\n    return Math.min(Infinity, ...this.#httpAttemptBudgets.map(budget => budget.limit - budget.dispatched));\n  }\n\n  #takeHttpAttempt(): boolean {\n    // No await between admission and debit: concurrent completions cannot spend the same last attempt.\n    if (this.#remainingHttpAttempts() < 1) return false;\n    for (const budget of this.#httpAttemptBudgets) budget.dispatched++;\n    return true;\n  }\n\n  async complete(request: NvidiaNimCompletionRequest): Promise<NvidiaNimCompletionResult> {\n    const requestId = typeof request.requestId === \"string\" && request.requestId.trim() ? request.requestId : \"MALFORMED\";\n    const responseFormat = responseFormatPayload(request.responseFormat);\n"],
    ["      const event: NvidiaNimCapacityProgress = Object.freeze({ state, requestDigest, observedAtEpochMs, retryAtEpochMs,\n        secondsUntilRetry: retryAtEpochMs === null ? null : Math.max(0, Math.ceil((retryAtEpochMs - observedAtEpochMs) / 1000)),\n        automaticResume: state === \"WAITING_FOR_CAPACITY\" && retryAtEpochMs !== null\n          && retryAtEpochMs < deadline && !signal.aborted,\n        httpAttempts, rateLimitedResponses, transientUnavailableResponses, timedOutAttempts,\n        taskCompletionClaimed: false, authorityRenewed: false });\n      try {\n","      const event: NvidiaNimCapacityProgress = Object.freeze({ state, requestDigest, observedAtEpochMs, retryAtEpochMs,\n        secondsUntilRetry: retryAtEpochMs === null ? null : Math.max(0, Math.ceil((retryAtEpochMs - observedAtEpochMs) / 1000)),\n        automaticResume: state === \"WAITING_FOR_CAPACITY\" && retryAtEpochMs !== null\n          && retryAtEpochMs < deadline && !signal.aborted && this.#remainingHttpAttempts() > 0,\n        httpAttempts, rateLimitedResponses, transientUnavailableResponses, timedOutAttempts,\n        taskCompletionClaimed: false, authorityRenewed: false });\n      try {\n"],
    ["      } catch { /* a failed status sink cannot alter delivery or expose its exception */ }\n    };\n    const finish = (result: NvidiaNimCompletionResult, notBeforeEpochMs: number | null = null): NvidiaNimCompletionResult => {\n      const delivery: NvidiaNimDeliveryEvidence = Object.freeze({ policy: \"nvidia-capacity/1\", requestsPerMinute: 40,\n        scope: \"PROCESS_LOCAL_FIXED_NVIDIA_ENDPOINT\", httpAttempts, rateLimitedResponses,\n        transientUnavailableResponses, timedOutAttempts, capacityWaitMs,\n        state: result.decision === \"COMPLETED\" ? \"DELIVERED\" : result.decision === \"WAITING_FOR_CAPACITY\" ? \"WAITING_FOR_CAPACITY\" : \"STOPPED\",\n        notBeforeEpochMs, authorityRenewed: false });\n      if (waitVisible) progress(result.decision === \"COMPLETED\" ? \"COMPLETED\" : \"STOPPED\", notBeforeEpochMs);\n      return Object.freeze({ ...result, evidence: Object.freeze({ ...result.evidence, delivery }) });\n    };\n","      } catch { /* a failed status sink cannot alter delivery or expose its exception */ }\n    };\n    const finish = (result: NvidiaNimCompletionResult, notBeforeEpochMs: number | null = null): NvidiaNimCompletionResult => {\n      const budget = this.#httpAttemptBudgets.at(-1);\n      const delivery: NvidiaNimDeliveryEvidence = Object.freeze({ policy: \"nvidia-capacity/1\", requestsPerMinute: 40,\n        scope: \"PROCESS_LOCAL_FIXED_NVIDIA_ENDPOINT\", httpAttempts, rateLimitedResponses,\n        transientUnavailableResponses, timedOutAttempts, capacityWaitMs,\n        state: result.decision === \"COMPLETED\" ? \"DELIVERED\" : result.decision === \"WAITING_FOR_CAPACITY\" ? \"WAITING_FOR_CAPACITY\" : \"STOPPED\",\n        notBeforeEpochMs, authorityRenewed: false,\n        ...(budget ? { httpAttemptBudget: Object.freeze({ scope: \"HOST_OWNED_RUN_INCLUDING_RETRIES\" as const,\n          limit: budget.limit, dispatched: budget.dispatched, remainingAttempts: this.#remainingHttpAttempts(),\n          exhausted: this.#remainingHttpAttempts() === 0,\n          dispatchDenied: result.reason === \"nvidia_http_attempt_budget_exhausted\", renewed: false as const }) } : {}) });\n      if (waitVisible) progress(result.decision === \"COMPLETED\" ? \"COMPLETED\" : \"STOPPED\", notBeforeEpochMs);\n      return Object.freeze({ ...result, evidence: Object.freeze({ ...result.evidence, delivery }) });\n    };\n"],
    ["    while (true) {\n      if (signal.aborted) return stopped(true);\n      if (now() >= deadline) return stopped(false);\n      if (this.#capacity) {\n        const admission = await this.#capacity.acquire(deadline, signal, (update) => {\n          if (update.reason !== \"PROVIDER_COOLDOWN\" && !waitVisible) return;\n","    while (true) {\n      if (signal.aborted) return stopped(true);\n      if (now() >= deadline) return stopped(false);\n      if (this.#remainingHttpAttempts() < 1) return finish(this.#result(\"BLOCKED\", \"nvidia_http_attempt_budget_exhausted\",\n        null, null, requestDigest, null, previous?.evidence.statusCode ?? null, emptyUsage(), httpAttempts > 0,\n        previous?.evidence.providerRequestId ?? null));\n      if (this.#capacity) {\n        const admission = await this.#capacity.acquire(deadline, signal, (update) => {\n          if (update.reason !== \"PROVIDER_COOLDOWN\" && !waitVisible) return;\n"],
    ["      if (signal.aborted) return stopped(true);\n      if (now() >= deadline) return stopped(false);\n      if (waiting) {\n        progress(\"RESUMING\"); waiting = false;\n        if (signal.aborted) return stopped(true);\n        if (now() >= deadline) return stopped(false);\n","      if (signal.aborted) return stopped(true);\n      if (now() >= deadline) return stopped(false);\n      if (waiting) {\n        if (this.#remainingHttpAttempts() < 1) return finish(this.#result(\"BLOCKED\", \"nvidia_http_attempt_budget_exhausted\",\n          null, null, requestDigest, null, previous?.evidence.statusCode ?? null, emptyUsage(), httpAttempts > 0,\n          previous?.evidence.providerRequestId ?? null));\n        progress(\"RESUMING\"); waiting = false;\n        if (signal.aborted) return stopped(true);\n        if (now() >= deadline) return stopped(false);\n"],
    ["  }\n\n  async #attempt(body: string, requestDigest: string, signal: AbortSignal, deadlineEpochMs: number): Promise<NvidiaNimCompletionResult> {\n    let credential: string | undefined;\n    try { credential = this.#config.credentialSource.read(); }\n    catch { return this.#result(\"BLOCKED\", \"nvidia_api_credential_unavailable\", null, null, requestDigest, null, null, emptyUsage(), false); }\n","  }\n\n  async #attempt(body: string, requestDigest: string, signal: AbortSignal, deadlineEpochMs: number): Promise<NvidiaNimCompletionResult> {\n    if (this.#remainingHttpAttempts() < 1) return this.#result(\"BLOCKED\", \"nvidia_http_attempt_budget_exhausted\",\n      null, null, requestDigest, null, null, emptyUsage(), false);\n    let credential: string | undefined;\n    try { credential = this.#config.credentialSource.read(); }\n    catch { return this.#result(\"BLOCKED\", \"nvidia_api_credential_unavailable\", null, null, requestDigest, null, null, emptyUsage(), false); }\n"],
    ["        .then(value => { cleanup(); resolve(value); }, error => { cleanup(); reject(error); });\n    });\n    try {\n      const response = await bounded(() => {\n        this.#capacity?.recordDispatch(); networkAttempted = true;\n        return this.#transport!(NVIDIA_NIM_CHAT_COMPLETIONS_URL, {\n          method: \"POST\",\n","        .then(value => { cleanup(); resolve(value); }, error => { cleanup(); reject(error); });\n    });\n    try {\n      let dispatchDeniedReason: string | null = null;\n      const response = await bounded(() => {\n        if ((this.#capacity?.clock.now() ?? Date.now()) >= deadlineEpochMs) {\n          dispatchDeniedReason = \"nvidia_completion_run_expired\"; return Promise.resolve(null);\n        }\n        if (!this.#takeHttpAttempt()) {\n          dispatchDeniedReason = \"nvidia_http_attempt_budget_exhausted\"; return Promise.resolve(null);\n        }\n        this.#capacity?.recordDispatch(); networkAttempted = true;\n        return this.#transport!(NVIDIA_NIM_CHAT_COMPLETIONS_URL, {\n          method: \"POST\",\n"],
    ["          signal: controller.signal,\n        });\n      });\n      const providerRequestId = safeProviderRequestId(response.headers.get(\"x-request-id\") ?? response.headers.get(\"request-id\"));\n      if (!response.ok) {\n        // Respect server recovery timing for transient outages as well as 429.\n","          signal: controller.signal,\n        });\n      });\n      if (response === null) return this.#result(\"BLOCKED\", dispatchDeniedReason!, null, null,\n        requestDigest, null, null, emptyUsage(), false);\n      const providerRequestId = safeProviderRequestId(response.headers.get(\"x-request-id\") ?? response.headers.get(\"request-id\"));\n      if (!response.ok) {\n        // Respect server recovery timing for transient outages as well as 429.\n"],
  ],
  [qualityPath]: [
    ['', '/** Read-only explanation of the existing detector, not another admission decision. */\nexport function measureEngineeringStructure(path: string, source: string, includeDeclarationSites = false) {\n  const value = analyze(path, source);\n  const sites: { kind: string; line: number; column: number; count: number }[] = [];\n  if (includeDeclarationSites) {\n    const file = ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true, scriptKind(path));\n    const visit = (node: ts.Node): void => {\n      const count = ts.isVariableStatement(node) ? node.declarationList.declarations.length\n        : ts.isFunctionDeclaration(node) || ts.isFunctionExpression(node) || ts.isArrowFunction(node)\n          || ts.isMethodDeclaration(node) ? 1 : 0;\n      if (count && sites.length < 48) {\n        const position = file.getLineAndCharacterOfPosition(node.getStart(file));\n        sites.push({ kind: ts.isVariableStatement(node) ? "VariableStatement" : ts.SyntaxKind[node.kind],\n          line: position.line + 1, column: position.character + 1, count });\n      }\n      ts.forEachChild(node, visit);\n    };\n    visit(file);\n  }\n  return Object.freeze({ parseable: value.parseErrors.length === 0, declarations: value.declarations,\n    complexity: value.complexity, maxNesting: value.maxNesting,\n    ...(includeDeclarationSites ? { declarationSites: Object.freeze(sites.map(site => Object.freeze(site))),\n      declarationSitesComplete: sites.reduce((sum, site) => sum + site.count, 0) === value.declarations } : {}) });\n}\n\n'],
  ],
  [cognitivePath]: [
    ['', 'import { measuredQualityRepairGuidance } from "./nyxMeasuredQualityGuidance";\n'],
    ['', '  /** Host-only experiment; default feedback and all acceptance gates remain unchanged. */\n  readonly qualityRepairGuidance?: "MEASURED_STRUCTURE" | "STRUCTURE_SITES";\n'],
    ['', '    if (config.qualityRepairGuidance !== undefined && !["MEASURED_STRUCTURE", "STRUCTURE_SITES"].includes(config.qualityRepairGuidance)) {\n      throw new Error("nyx_quality_repair_guidance_invalid");\n    }\n'],
    ['', '      ...(this.#config.qualityRepairGuidance && qualityFeedback\n        ? { measuredQualityRepair: measuredQualityRepairGuidance(request, this.#config.qualityRepairGuidance === "STRUCTURE_SITES") } : {}),\n'],
    ['function providerCompatibleSchema(value: unknown): unknown {\n  if (Array.isArray(value)) return Object.freeze(value.map(providerCompatibleSchema));\n',
      'function providerCompatibleSchema(value: unknown, preserveArrayBounds = true): unknown {\n  if (Array.isArray(value)) return Object.freeze(value.map(item => providerCompatibleSchema(item, preserveArrayBounds)));\n'],
    ['    .filter(([key]) => !LOCALLY_ENFORCED_SCHEMA_KEYWORDS.has(key))\n',
      '    .filter(([key]) => !LOCALLY_ENFORCED_SCHEMA_KEYWORDS.has(key) || (key === "maxItems" && preserveArrayBounds))\n'],
    ['      ? Object.freeze(Object.fromEntries(Object.entries(item).map(([name, schema]) => [name, providerCompatibleSchema(schema)])))\n      : providerCompatibleSchema(item)])));\n',
      '      ? Object.freeze(Object.fromEntries(Object.entries(item).map(([name, schema]) => [name, providerCompatibleSchema(schema, preserveArrayBounds)])))\n      : providerCompatibleSchema(item, preserveArrayBounds)])));\n'],
    ['export function buildNyxRepairIntentContract(request: NyxRepairCognitionRequest, sourceRepresentation: NyxSourceRepresentation = "TEXT") {\n',
      'export function buildNyxRepairIntentContract(request: NyxRepairCognitionRequest, sourceRepresentation: NyxSourceRepresentation = "TEXT", preserveProviderArrayBounds = true) {\n'],
    ['    schema, providerSchema: providerCompatibleSchema(schema) as Readonly<Record<string, unknown>>,\n',
      '    schema, providerSchema: providerCompatibleSchema(schema, preserveProviderArrayBounds) as Readonly<Record<string, unknown>>,\n'],
    ['', '  /** Host-only legacy ablation. E4 probes established omitted hosted arrays stop at 32 items. */\n  readonly preserveProviderArrayBounds?: boolean;\n'],
    ['', '    if (config.preserveProviderArrayBounds !== undefined && typeof config.preserveProviderArrayBounds !== "boolean") {\n      throw new Error("nyx_provider_array_bounds_policy_invalid");\n    }\n'],
    ['', '  /** Host-only delivery control. Local intent, syntax, scope and quality checks remain mandatory. */\n  readonly structuredOutputMode?: "STRICT_LOCAL";\n'],
    ['', '    if (config.structuredOutputMode !== undefined && config.structuredOutputMode !== "STRICT_LOCAL") {\n      throw new Error("nyx_structured_output_mode_invalid");\n    }\n'],
    ['', '      ...(this.#config.structuredOutputMode === "STRICT_LOCAL" ? { structuredOutputMode: "STRICT_LOCAL" as const } : {}),\n'],
    ['    const contract = buildNyxRepairIntentContract(request, this.#sourceRepresentation);\n',
      '    const contract = buildNyxRepairIntentContract(request, this.#sourceRepresentation, this.#config.preserveProviderArrayBounds);\n', 2],
    ['', '  /** Explicit comparison control. Omission preserves each established variant\'s inference policy. */\n  readonly comparisonInferencePolicy?: "CONSTRAINED_JSON" | "REASONING_JSON";\n'],
    ['', '    if (config.comparisonInferencePolicy !== undefined\n      && !["CONSTRAINED_JSON", "REASONING_JSON"].includes(config.comparisonInferencePolicy)) {\n      throw new Error("nyx_comparison_inference_policy_invalid");\n    }\n'],
    ['      inferencePolicy: this.#experimentVariant === "CURRENT" ? "CONSTRAINED_JSON" : "REASONING_JSON",\n',
      '      inferencePolicy: this.#config.comparisonInferencePolicy\n        ?? (this.#experimentVariant === "CURRENT" ? "CONSTRAINED_JSON" : "REASONING_JSON"),\n'],
  ],
  [loopPath]: [
    ['', '  /** Outer experiment cancellation never renews the loop\'s deadline or grants authority. */\n  readonly signal?: AbortSignal;\n'],
    ['\n', '\n      if (request.signal?.aborted) return finish("EXHAUSTED", "repair_outer_request_aborted", iterations, currentObservation);\n'],
    ['        observedAtEpochMs: Math.max(request.observedAtEpochMs, Date.now()) });\n',
      '        observedAtEpochMs: Math.max(request.observedAtEpochMs, Date.now()), signal: request.signal });\n'],
    ['      if (Date.now() - started >= this.#config.maxWallClockMs) {\n',
      '      if (request.signal?.aborted || Date.now() - started >= this.#config.maxWallClockMs) {\n'],
    ['\n', '\n        if (request.signal?.aborted) return finish("EXHAUSTED", "repair_outer_request_aborted", iterations, currentObservation);\n'],
  ],
};
const finalAttemptRefinement: readonly (readonly [string, string])[] = [
  [
    "  readonly maxOutputTokens: number;\n  readonly timeoutMs: number;\n  readonly transport?: NvidiaNimTransport;\n  /** Deterministic delivery testing only. Live instances always share the process-local gate. */\n",
    "  readonly maxOutputTokens: number;\n  readonly timeoutMs: number;\n  /** Host-only experiment: the last shared-budget attempt may wait longer, but never beyond the caller's existing lease. */\n  readonly finalAttemptTimeoutMs?: number;\n  readonly transport?: NvidiaNimTransport;\n  /** Deterministic delivery testing only. Live instances always share the process-local gate. */\n"
  ],
  [
    "  readonly notBeforeEpochMs: number | null;\n  readonly authorityRenewed: false;\n  /** Host-owned dispatch budget shared by logical calls and retries, never supplied to the model. */\n  readonly httpAttemptBudget?: {\n",
    "  readonly notBeforeEpochMs: number | null;\n  readonly authorityRenewed: false;\n  /** Explicit host delivery profile; the original absolute deadline is not renewed. */\n  readonly attemptTimeout?: {\n    readonly configuredMs: number;\n    readonly finalAttemptMs: number;\n    readonly callerDeadlineEpochMs: number;\n    readonly finalAttemptUsed: boolean;\n    readonly authorityRenewed: false;\n  };\n  /** Host-owned dispatch budget shared by logical calls and retries, never supplied to the model. */\n  readonly httpAttemptBudget?: {\n"
  ],
  [
    "      || !Number.isInteger(config.maxOutputTokens) || config.maxOutputTokens < 1 || config.maxOutputTokens > 32_768\n      || !Number.isInteger(config.timeoutMs) || config.timeoutMs < 100 || config.timeoutMs > 120_000) throw new Error(\"provider_resource_policy_invalid\");\n    if (config.authorityMode === \"TEST_DOUBLE_ONLY\" && !config.transport) throw new Error(\"test_double_transport_required\");\n    if (config.authorityMode !== \"TEST_DOUBLE_ONLY\" && config.authorityMode !== \"EXPLICIT_LIVE_NVIDIA_NIM\") throw new Error(\"provider_authority_mode_invalid\");\n",
    "      || !Number.isInteger(config.maxOutputTokens) || config.maxOutputTokens < 1 || config.maxOutputTokens > 32_768\n      || !Number.isInteger(config.timeoutMs) || config.timeoutMs < 100 || config.timeoutMs > 120_000) throw new Error(\"provider_resource_policy_invalid\");\n    if (config.finalAttemptTimeoutMs !== undefined && (!Number.isSafeInteger(config.finalAttemptTimeoutMs)\n      || config.finalAttemptTimeoutMs < config.timeoutMs || config.finalAttemptTimeoutMs > 180_000)) {\n      throw new Error(\"provider_final_attempt_timeout_invalid\");\n    }\n    if (config.authorityMode === \"TEST_DOUBLE_ONLY\" && !config.transport) throw new Error(\"test_double_transport_required\");\n    if (config.authorityMode !== \"TEST_DOUBLE_ONLY\" && config.authorityMode !== \"EXPLICIT_LIVE_NVIDIA_NIM\") throw new Error(\"provider_authority_mode_invalid\");\n"
  ],
  [
    "      issues.push(\"completion_deadline_invalid\");\n    }\n    if (!validMessages(request.messages)) issues.push(\"completion_messages_invalid\");\n    if (!Number.isInteger(request.maxTokens) || request.maxTokens < 1 || request.maxTokens > this.#config.maxOutputTokens) issues.push(\"completion_token_bound_exceeded\");\n",
    "      issues.push(\"completion_deadline_invalid\");\n    }\n    if (this.#config.finalAttemptTimeoutMs !== undefined\n      && (request.deadlineEpochMs === undefined || this.#httpAttemptBudgets.length === 0)) {\n      issues.push(\"completion_final_attempt_requires_owned_budget_and_deadline\");\n    }\n    if (!validMessages(request.messages)) issues.push(\"completion_messages_invalid\");\n    if (!Number.isInteger(request.maxTokens) || request.maxTokens < 1 || request.maxTokens > this.#config.maxOutputTokens) issues.push(\"completion_token_bound_exceeded\");\n"
  ],
  [
    "    let timedOutAttempts = 0;\n    let capacityWaitMs = 0;\n    let previous: NvidiaNimCompletionResult | null = null;\n    let waitVisible = false;\n",
    "    let timedOutAttempts = 0;\n    let capacityWaitMs = 0;\n    let finalAttemptTimeoutUsed = false;\n    let previous: NvidiaNimCompletionResult | null = null;\n    let waitVisible = false;\n"
  ],
  [
    "        state: result.decision === \"COMPLETED\" ? \"DELIVERED\" : result.decision === \"WAITING_FOR_CAPACITY\" ? \"WAITING_FOR_CAPACITY\" : \"STOPPED\",\n        notBeforeEpochMs, authorityRenewed: false,\n        ...(budget ? { httpAttemptBudget: Object.freeze({ scope: \"HOST_OWNED_RUN_INCLUDING_RETRIES\" as const,\n          limit: budget.limit, dispatched: budget.dispatched, remainingAttempts: this.#remainingHttpAttempts(),\n",
    "        state: result.decision === \"COMPLETED\" ? \"DELIVERED\" : result.decision === \"WAITING_FOR_CAPACITY\" ? \"WAITING_FOR_CAPACITY\" : \"STOPPED\",\n        notBeforeEpochMs, authorityRenewed: false,\n        ...(this.#config.finalAttemptTimeoutMs !== undefined ? { attemptTimeout: Object.freeze({\n          configuredMs: this.#config.timeoutMs, finalAttemptMs: this.#config.finalAttemptTimeoutMs,\n          callerDeadlineEpochMs: request.deadlineEpochMs!, finalAttemptUsed: finalAttemptTimeoutUsed,\n          authorityRenewed: false as const }) } : {}),\n        ...(budget ? { httpAttemptBudget: Object.freeze({ scope: \"HOST_OWNED_RUN_INCLUDING_RETRIES\" as const,\n          limit: budget.limit, dispatched: budget.dispatched, remainingAttempts: this.#remainingHttpAttempts(),\n"
  ],
  [
    "        if (now() >= deadline) return stopped(false);\n      }\n      previous = await this.#attempt(body, requestDigest, signal, deadline);\n      if (previous.evidence.networkAttempted) httpAttempts += 1;\n",
    "        if (now() >= deadline) return stopped(false);\n      }\n      if (this.#config.finalAttemptTimeoutMs !== undefined && this.#remainingHttpAttempts() === 1) finalAttemptTimeoutUsed = true;\n      previous = await this.#attempt(body, requestDigest, signal, deadline);\n      if (previous.evidence.networkAttempted) httpAttempts += 1;\n"
  ],
  [
    "    let timeoutTriggered = false;\n    let networkAttempted = false;\n    const timeout = setTimeout(() => { timeoutTriggered = true; controller.abort(); }, Math.min(this.#config.timeoutMs, remainingMs));\n    const bounded = <T>(operation: () => Promise<T>): Promise<T> => new Promise((resolve, reject) => {\n      const aborted = () => { cleanup(); reject(new DOMException(\"Provider request aborted\", \"AbortError\")); };\n",
    "    let timeoutTriggered = false;\n    let networkAttempted = false;\n    const attemptTimeoutMs = this.#remainingHttpAttempts() === 1\n      ? this.#config.finalAttemptTimeoutMs ?? this.#config.timeoutMs : this.#config.timeoutMs;\n    const timeout = setTimeout(() => { timeoutTriggered = true; controller.abort(); }, Math.min(attemptTimeoutMs, remainingMs));\n    const bounded = <T>(operation: () => Promise<T>): Promise<T> => new Promise((resolve, reject) => {\n      const aborted = () => { cleanup(); reject(new DOMException(\"Provider request aborted\", \"AbortError\")); };\n"
  ]
];
/** Invert only the declared exact hunks. Hash/compare the WHOLE result with the frozen predecessor. */
export function arcCorePredecessorSource(path: string, current: string): string {
  if (!changes[path]) return current;
  if (path === "src/lib/codelab/model/nvidiaNimProvider.ts") for (const [before, after] of finalAttemptRefinement) {
    if (current.split(after).length !== 2) throw Error("arc_final_attempt_refinement_hunk_mismatch");
    current = current.split(after).join(before);
  }
  for (const [before, after, expectedCount = 1] of changes[path]) {
    if (current.split(after).length !== expectedCount + 1) throw Error("arc_core_refinement_hunk_mismatch");
    current = current.split(after).join(before);
  }
  return current;
}
