import { OMEGA_R1_TRACEABLE_BASELINE_COMMIT } from "../registry/baselineGenealogy";

export const R1_REPLICATION_REQUIREMENTS = Object.freeze([
  "CLEAN_CHECKOUT", "EXACT_CANDIDATE", "EXACT_SUITE_MANIFEST", "INDEPENDENT_ENVIRONMENT_IDENTITY",
  "NO_LOCAL_DEVELOPER_STATE", "READ_ONLY_AUTHORITY", "R1_PRIVATE_EVALUATOR", "INTEGRATED_RO_VERTICAL_SLICE",
  "HOST_ALIAS_EQUIVALENT_WHERE_SUPPORTED", "EVIDENCE_CUSTODY", "OUTPUT_MANIFEST",
] as const);
export type R1ReplicationRequirement=(typeof R1_REPLICATION_REQUIREMENTS)[number];
export interface R1ReplicationSpecification {
  readonly schemaVersion:1; readonly specificationId:"OMEGA-R1-REPLICATION-SPEC-001"; readonly maturity:"SPECIFIED"; readonly executionState:"NOT_EXECUTED";
  readonly candidateCommit:"68717200b669a8e7644e01f717f158ea44899820"; readonly authorityCeiling:"READ_REPOSITORY"; readonly requiredEvidenceClass:"E4_OR_E5_DEPENDING_ON_OWNER";
  readonly requirements:readonly R1ReplicationRequirement[]; readonly prohibitedAssumptions:readonly string[]; readonly environmentPolicy:{readonly deno:"BLOCKED_ENVIRONMENT_NOT_REQUIRED";readonly liveNetwork:"NOT_AUTHORIZED_NOT_EXECUTED";readonly externalApi:"NOT_AUTHORIZED_NOT_EXECUTED"};
  readonly requiredOutputFields:readonly string[]; readonly grantsAuthority:false;
}
export interface R1ReplicationManifest { readonly schemaVersion:1; readonly replicationId:string; readonly candidateCommit:string; readonly suiteManifestDigest:string; readonly environmentIdentity:string; readonly installedTools:Readonly<Record<string,string>>; readonly executedRequirements:readonly R1ReplicationRequirement[]; readonly blockedRequirements:readonly string[]; readonly skippedRequirements:readonly string[]; readonly authority:"READ_REPOSITORY"; readonly evidenceRefs:readonly string[] }
export function validateR1ReplicationSpecification(spec:R1ReplicationSpecification):readonly string[]{const issues:string[]=[];if(spec.schemaVersion!==1||spec.specificationId!=="OMEGA-R1-REPLICATION-SPEC-001")issues.push("wrong_replication_spec_identity");if(spec.maturity!=="SPECIFIED"||spec.executionState!=="NOT_EXECUTED")issues.push("replication_execution_overclaim");for(const requirement of R1_REPLICATION_REQUIREMENTS)if(!spec.requirements.includes(requirement))issues.push(`missing_requirement:${requirement}`);if(spec.authorityCeiling!=="READ_REPOSITORY"||spec.grantsAuthority)issues.push("replication_authority_inflated");if(spec.environmentPolicy.deno!=="BLOCKED_ENVIRONMENT_NOT_REQUIRED"||spec.environmentPolicy.liveNetwork!=="NOT_AUTHORIZED_NOT_EXECUTED")issues.push("blocked_environment_misrepresented");for(const field of ["replicationId","candidateCommit","suiteManifestDigest","environmentIdentity","installedTools","executedRequirements","blockedRequirements","skippedRequirements","authority","evidenceRefs"])if(!spec.requiredOutputFields.includes(field))issues.push(`missing_output_field:${field}`);return[...new Set(issues)]}
export function assessR1ReplicationManifest(manifest:R1ReplicationManifest,spec:R1ReplicationSpecification=OMEGA_R1_REPLICATION_SPEC_001):{readonly decision:"COMPLETE_RECORD"|"INCOMPLETE_RECORD"|"WRONG_CANDIDATE";readonly reasons:readonly string[];readonly replicationAccepted:false}{const reasons:string[]=[];if(manifest.candidateCommit!==spec.candidateCommit)return{decision:"WRONG_CANDIDATE",reasons:["candidate_binding_mismatch"],replicationAccepted:false};if(manifest.schemaVersion!==1||!manifest.replicationId.trim()||!/^[0-9a-f]{64}$/.test(manifest.suiteManifestDigest)||!manifest.environmentIdentity.trim()||Object.keys(manifest.installedTools).length===0||manifest.evidenceRefs.length===0)reasons.push("manifest_identity_or_provenance_incomplete");for(const requirement of spec.requirements)if(!manifest.executedRequirements.includes(requirement)&&!manifest.blockedRequirements.includes(requirement)&&!manifest.skippedRequirements.includes(requirement))reasons.push(`requirement_outcome_missing:${requirement}`);if(manifest.authority!=="READ_REPOSITORY")reasons.push("replication_authority_changed");return{decision:reasons.length?"INCOMPLETE_RECORD":"COMPLETE_RECORD",reasons:[...new Set(reasons)],replicationAccepted:false}}
export const OMEGA_R1_REPLICATION_SPEC_001=Object.freeze<R1ReplicationSpecification>({schemaVersion:1,specificationId:"OMEGA-R1-REPLICATION-SPEC-001",maturity:"SPECIFIED",executionState:"NOT_EXECUTED",candidateCommit:OMEGA_R1_TRACEABLE_BASELINE_COMMIT,authorityCeiling:"READ_REPOSITORY",requiredEvidenceClass:"E4_OR_E5_DEPENDING_ON_OWNER",requirements:R1_REPLICATION_REQUIREMENTS,prohibitedAssumptions:["local untracked files","developer-global configuration","preexisting dependency cache as proof","network availability","unrecorded manual repair"],environmentPolicy:{deno:"BLOCKED_ENVIRONMENT_NOT_REQUIRED",liveNetwork:"NOT_AUTHORIZED_NOT_EXECUTED",externalApi:"NOT_AUTHORIZED_NOT_EXECUTED"},requiredOutputFields:["replicationId","candidateCommit","suiteManifestDigest","environmentIdentity","installedTools","executedRequirements","blockedRequirements","skippedRequirements","authority","evidenceRefs"],grantsAuthority:false});
