import type {
  CapabilityCertificate,
  Criterion,
  EvidenceRecord,
  MaturityAttestation,
  MaturityState,
  OmegaRegistry,
  SecurityProfile,
  SourceProvenance,
} from "./types";

const DIRECTIVE_SOURCE: SourceProvenance = Object.freeze({
  sourceId: "Ω-SOURCE-DIRECTIVE-002",
  sourceType: "conversation",
  locator: "conversation://omega-institutional-execution-directive-002",
  contentHash: null,
});

const DIRECTIVE_003_SOURCE: SourceProvenance = Object.freeze({
  sourceId: "Ω-SOURCE-DIRECTIVE-003",
  sourceType: "conversation",
  locator: "conversation://omega-institutional-execution-directive-003",
  contentHash: null,
});

const DIRECTIVE_004_SOURCE: SourceProvenance = Object.freeze({
  sourceId: "Ω-SOURCE-DIRECTIVE-004",
  sourceType: "conversation",
  locator: "conversation://omega-institutional-execution-directive-004",
  contentHash: null,
});

const REPOSITORY_SOURCE: SourceProvenance = Object.freeze({
  sourceId: "Ω-SOURCE-REPOSITORY",
  sourceType: "repository",
  locator: "repository://generous-ai-core/sol/omega-institutional-spine",
  contentHash: null,
});

function criterion(id: string, statement: string, measurement: string, threshold: string): Criterion {
  return { criterionId: id, statement, measurement, threshold };
}

function evidence(
  evidenceId: string,
  evidenceClass: EvidenceRecord["evidenceClass"],
  claim: string,
  artifactRef: string,
  mechanism: string,
  independenceBasis: string | null,
  provenance: SourceProvenance = REPOSITORY_SOURCE,
): EvidenceRecord {
  return {
    evidenceId,
    evidenceClass,
    result: "SUPPORTS",
    claim,
    provenance,
    artifactRef,
    mechanism,
    freshness: "CURRENT",
    independenceBasis,
  };
}

function maturityHistory(states: readonly MaturityState[], verifiedEvidenceId?: string): readonly MaturityAttestation[] {
  return states.map((state) => ({
    state,
    evidenceIds: ["VERIFIED", "INDEPENDENTLY_REPLICATED", "PRODUCTION_READY", "ROUTINIZED"].includes(state) && verifiedEvidenceId
      ? [verifiedEvidenceId]
      : [],
    rationale: `Institutional maturity gate ${state} recorded explicitly.`,
  }));
}

function securityProfile(evidenceIds: readonly string[], privilege = "No runtime privilege"): SecurityProfile {
  return {
    threatModel: ["Dishonest or stale institutional state", "Tampered or correlated evidence"],
    privilegeRequirements: [privilege],
    dataSensitivity: "INTERNAL",
    isolationRequirements: ["Repository-scoped implementation", "No credential access"],
    attackSurface: ["Registry input", "Evidence provenance", "Serialization boundary"],
    trustAssumptions: ["Git object identity is available", "Deterministic tests execute without mutation"],
    possibleMisuse: ["Inflating maturity", "Claiming corpus completeness", "Treating correlated evidence as independent"],
    compromisePaths: ["Malformed registry object", "Falsified evidence reference"],
    blastRadius: "Institutional planning and capability claims; no direct execution authority.",
    containmentMechanisms: ["Runtime validation", "Explicit maturity gates", "Evidence-class checks"],
    rollbackMechanisms: ["Revert registry commit", "Restore prior verified registry snapshot"],
    securityEvidenceIds: evidenceIds,
  };
}

function capabilityCertificate(
  certificateId: string,
  title: string,
  evidenceId: string,
  result: string,
): CapabilityCertificate {
  return {
    certificateId,
    title,
    maturity: "VERIFIED",
    epistemicState: "SUPPORTED",
    verificationState: "VERIFIED",
    evidenceIds: [evidenceId],
    threshold: "All assigned held-out checks pass with zero false acceptance",
    result,
    confidence: 1,
  };
}

const directiveEvidence = evidence(
  "Ω-EV-DIRECTIVE-002",
  "E0",
  "The institutional authority specified REG-001A and VS-001A requirements.",
  DIRECTIVE_SOURCE.locator,
  "Explicit institutional directive",
  null,
  DIRECTIVE_SOURCE,
);
const directive003Evidence = evidence(
  "Ω-EV-DIRECTIVE-003",
  "E0",
  "The institutional authority specified credential containment, private R1 evaluation, and R2 design requirements.",
  DIRECTIVE_003_SOURCE.locator,
  "Explicit institutional directive",
  null,
  DIRECTIVE_003_SOURCE,
);
const directive004Evidence = evidence(
  "Ω-EV-DIRECTIVE-004",
  "E0",
  "The institutional authority kept security containment as the controlling gate and required R2-A specification/evaluation without authority.",
  DIRECTIVE_004_SOURCE.locator,
  "Explicit institutional directive",
  null,
  DIRECTIVE_004_SOURCE,
);
const secProjectIdentityEvidence = evidence(
  "Ω-EV-SEC-003-PROJECT-IDENTIFIED",
  "E3",
  "Repository configuration identifies the linked Supabase project without reproducing credential material.",
  "repository://sanitized-environment-project-reference",
  "Sanitized repository-configuration inspection",
  "The repository configuration is external to the registry claim and the evidence excludes credential bytes.",
);
const secManagementAccessEvidence = evidence(
  "Ω-EV-SEC-003-MANAGEMENT-ACCESS-BLOCKED",
  "E4",
  "The authenticated Supabase management session redirected away from the repository-linked project and exposed only an unrelated project.",
  "external-observation://supabase-dashboard-access-check-2026-08-24",
  "Read-only authenticated management-plane observation",
  "The live Supabase dashboard determined project visibility independently from repository and registry assertions; no credential state was inferred.",
);
const registryEvidence = evidence(
  "Ω-EV-REGISTRY-TESTS",
  "E3",
  "Registry invariants pass the deterministic registry harness.",
  "command://npm-run-omega-tests",
  "Node 24 deterministic test harness",
  "The runtime checker executes independently from stored registry claims.",
);
const readOnlyExecutorEvidence = evidence(
  "Ω-EV-VS-READ-ONLY-34",
  "E3",
  "The R1 executor passed 34 scoped, attributable, auditable, revocable, and epistemically honest repository-observation checks, including a live package.json read.",
  "command://npm-run-omega-tests",
  "Node 24 executor adversarial harness with live repository observation",
  "The filesystem and deterministic harness produce observations independently from stored capability claims; harness-oracle correlation remains acknowledged.",
);
const r1BaselineEvidence = evidence(
  "Ω-EV-R1-BASELINE-7729CF3",
  "E3",
  "Commit 7729cf3 is the immutable comparison point for the locally verified R1 executor foundation.",
  "git://generous-ai-core/commit/7729cf3e3e6bdb9e8771dfcad6386ecc9fa55296",
  "Git object identity and pushed upstream equality",
  "Git independently identifies the exact repository state; it does not independently validate capability semantics.",
);
const r1PrivateEvaluationEvidence = evidence(
  "Ω-EV-EVAL-R1-PRIVATE-31",
  "E3",
  "A fresh evaluator-owned repository corpus passed 31 held-out checks across R1-A through R1-J, including a real Windows junction escape attempt.",
  "command://omega-r1-private-evaluation",
  "Separate temporary-repository generator, direct host-filesystem oracle, and capability-certificate harness",
  "The evaluator does not import executor normalization or audit validators and discovered a root-path defect before the corrected rerun; model-author correlation remains acknowledged.",
);
const orchestraEvidence = evidence(
  "Ω-EV-ORCHESTRA-385",
  "E3",
  "The deterministic ORCHESTRA contract suite reports 385 passed and zero failed checks.",
  "command://npm-run-omega-tests",
  "Node 24 deterministic test harness",
  "Execution is deterministic, while oracle-design correlation remains explicitly acknowledged.",
);
const secretEvidence = evidence(
  "Ω-EV-SECRET-SCAN",
  "E3",
  "The tracked-file high-confidence secret scan reports zero findings.",
  "command://npm-run-security-secrets",
  "Deterministic tracked-file scanner",
  "The scanner operates on Git-tracked bytes rather than generator self-report.",
);
const r2DesignEvidence = evidence(
  "Ω-EV-R2-DESIGN-51",
  "E3",
  "The isolated-write design passed 51 deterministic contract and assurance-gate checks without exposing an operational write primitive.",
  "command://omega-r2-design-tests",
  "Node 24 pure contract harness over sandbox design, mutation transactions, rollback proofs, and evidence chains",
  "The executable validator is separate from institutional narrative claims, while implementation-oracle and same-author correlation remain acknowledged.",
);
const r2ASpecEvidence = evidence(
  "Ω-EV-R2-A-SPEC-EVAL-51",
  "E3",
  "The R2-A provisioning specification and evaluator passed 51 deterministic contract checks while exposing no filesystem adapter or operational authority.",
  "command://omega-r2-a-spec-eval-tests",
  "Node 24 pure contract harness over provisioning requests, identity stability, cleanup equivalence, authority composition, and gate state",
  "The executable validator is separate from stored registry claims; implementation-oracle and same-author correlation remain acknowledged.",
);
const tsRatchetEvidence = evidence(
  "Ω-EV-TS-RATCHET-16",
  "E3",
  "The full-project TypeScript ratchet reproduced seven accepted diagnostics from d2b7121 and reported zero new diagnostics; its deterministic parser/comparator harness passed 16 checks.",
  "command://npm-run-typecheck-ratchet",
  "TypeScript 5.8.3 compiler plus multiset diagnostic comparison against an exact-commit baseline",
  "The TypeScript compiler produces diagnostics independently from the registry claim; baseline-selection and fingerprint design remain same-author decisions.",
);

export const OMEGA_BASELINE_REGISTRY: OmegaRegistry = Object.freeze({
  schemaVersion: 1,
  corpusStatus: "PARTIAL",
  losslessCertification: false,
  plans: [
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-REG-001A",
      originalSourceId: "Ω-REG-001A",
      title: "Minimum Executable Registry",
      source: DIRECTIVE_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        registryEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directiveEvidence, registryEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-REG-VALID", "Valid registry records are accepted.", "Deterministic registry harness", "All valid fixtures accepted"),
        criterion("Ω-AC-REG-DISHONEST", "Dishonest state combinations are rejected.", "Adversarial invariant fixtures", "All defined invalid combinations rejected"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-REG-BYPASS", "A malformed or dishonest object bypasses validation.", "Adversarial registry harness", "Any bypass falsifies the claim"),
      ],
      dependencies: [],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/registry", status: "active" },
        { kind: "tool", ref: "scripts/omegaRegistry.test.ts", status: "active" },
      ],
      securityProfile: securityProfile([registryEvidence.evidenceId]),
      researchMaturity: "EXPERIMENT_RUN",
      hypothesis: {
        statement: "Machine-enforced registry invariants reduce dishonest institutional state combinations.",
        supportCriterion: "Defined invalid maturity, corpus, and evidence combinations are rejected.",
        falsificationCriterion: "Any defined dishonest combination is accepted without an explicit error.",
        baseline: "Unstructured narrative status records",
        competingExplanations: ["Tests merely mirror the implementation", "Manual review provides equivalent protection"],
        measurementMethod: "Deterministic valid and adversarial fixture execution",
        requiredPopulation: "Every required Directive-002 invariant plus serialization and relationship cases",
        computeBudget: "Single local CPU process; no model inference",
        calibrationRequirement: "No probabilistic confidence claim; exact acceptance/rejection outcomes",
      },
      relationships: [{ kind: "OVERLAPS", targetId: "Ω-PLAN-VS-001A" }],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-VS-001A",
      originalSourceId: "Ω-VS-001A",
      title: "Read-Only Live Executor",
      source: DIRECTIVE_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        readOnlyExecutorEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directiveEvidence, readOnlyExecutorEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-VS-SCOPED", "Repository observations are scoped and auditable.", "Adversarial executor harness", "All required authorization cases pass"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-VS-ESCAPE", "Executor reads outside authorized scope or omits an action.", "Traversal and audit adversary", "Any unauthorized read or omitted action falsifies the claim"),
      ],
      dependencies: ["Ω-PLAN-REG-001A"],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/executor", status: "active" },
        { kind: "tool", ref: "scripts/omegaReadOnlyExecutor.test.ts", status: "active" },
      ],
      securityProfile: securityProfile([readOnlyExecutorEvidence.evidenceId], "R1 scoped repository read only"),
      researchMaturity: "EXPERIMENT_RUN",
      relationships: [{ kind: "OVERLAPS", targetId: "Ω-PLAN-REG-001A" }],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-EVAL-R1-001",
      originalSourceId: "Ω-EVAL-R1-001",
      title: "Independent Private R1 Evaluation",
      source: DIRECTIVE_003_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        r1PrivateEvaluationEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directive003Evidence, r1PrivateEvaluationEvidence, r1BaselineEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-EVAL-R1-HELDOUT", "Fresh evaluator-owned repository cases pass against independent expected outcomes.", "Private R1 evaluation harness", "All assigned checks pass"),
        criterion("Ω-AC-EVAL-R1-ALIAS", "A real host filesystem alias cannot escape the canonical repository root.", "Real junction or symlink fixture", "Escape rejected without content or target disclosure"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-EVAL-R1-ESCAPE", "Any held-out request observes content outside its authorization.", "Private adversarial fixture", "Any unauthorized observation falsifies R1 confinement"),
        criterion("Ω-FC-EVAL-R1-CORRELATION", "The independent oracle fails to reveal any behavior beyond the unit harness.", "Defect-discovery comparison", "No differentiated case coverage or fault discovery"),
      ],
      dependencies: ["Ω-PLAN-VS-001A", "Ω-CAP-READ-REPOSITORY"],
      implementationMappings: [
        { kind: "tool", ref: "scripts/evaluation/omegaR1PrivateEval.ts", status: "active" },
        { kind: "repository", ref: "src/lib/codelab/executor/readOnlyExecutor.ts", status: "active" },
      ],
      securityProfile: securityProfile([r1PrivateEvaluationEvidence.evidenceId], "R1 scoped read over evaluator-owned disposable repositories"),
      researchMaturity: "EXPERIMENT_RUN",
      hypothesis: {
        statement: "A fresh, separately oracled repository suite reveals R1 failures hidden by implementation-adjacent unit tests.",
        supportCriterion: "The evaluator discovers at least one real behavioral gap or materially expands host-filesystem evidence at matched authority.",
        falsificationCriterion: "The evaluator adds no differentiated coverage and no independent behavioral information.",
        baseline: "34 implementation-adjacent R1 unit checks at commit 7729cf3",
        competingExplanations: ["Additional cases improve only test volume", "The same model author preserves correlated assumptions"],
        measurementMethod: "Fresh temporary repository construction, direct host-filesystem expectations, and R1-A through R1-J certificates",
        requiredPopulation: "Nested, ignored, Unicode, generated, bounded, malformed, nested-Git, alias, expired, revoked, and adversarial scope cases",
        computeBudget: "Single local CPU process; no model inference and no network",
        calibrationRequirement: "Exact outcomes; host alias unsupported state must be reported PARTIAL rather than inferred",
      },
      relationships: [{ kind: "OVERLAPS", targetId: "Ω-PLAN-VS-001A" }],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-SEC-003",
      originalSourceId: "Ω-SEC-003",
      title: "Credential Containment and Remote-Tip Remediation",
      source: DIRECTIVE_003_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "PROPOSED",
      maturityHistory: maturityHistory(["PROPOSED"], directive003Evidence.evidenceId),
      epistemicState: "UNKNOWN",
      verificationState: "UNVERIFIED",
      evidence: [directive003Evidence, directive004Evidence, secProjectIdentityEvidence, secManagementAccessEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-SEC-003-MGMT", "The exposed credential is authoritatively revoked, rotated, or confirmed invalid.", "Supabase management-plane or database-backed evidence", "REVOKED_AND_VERIFIED, ROTATED_AND_VERIFIED, or CONFIRMED_INVALID"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-SEC-003-UNKNOWN", "Repository redaction alone is presented as credential containment.", "Management evidence comparison", "No authoritative credential-state evidence exists"),
      ],
      dependencies: ["Ω-CAP-TRACKED-SECRET-DETECTION"],
      implementationMappings: [{ kind: "process", ref: "Authorized Supabase management-plane credential containment", status: "experimental" }],
      securityProfile: {
        threatModel: ["An exposed credential remains valid or was misused.", "Secret material is reproduced during investigation."],
        privilegeRequirements: ["Authorized Supabase credential-management operator"],
        dataSensitivity: "RESTRICTED",
        isolationRequirements: ["Never expose credential bytes to chat, source, logs, screenshots, or fixtures."],
        attackSurface: ["Supabase management plane", "remote Git tips and retained history"],
        trustAssumptions: ["Only authoritative management evidence can establish credential state."],
        possibleMisuse: ["Unauthorized revocation", "secret reconstruction", "premature history rewrite"],
        compromisePaths: ["Previously published remote tip", "dependent integration configuration"],
        blastRadius: "Unknown until an authorized operator inspects credential status and usage.",
        containmentMechanisms: ["Revoke first; redact current tips only after containment; assess history separately."],
        rollbackMechanisms: ["Credential replacement and dependent integration rotation; retain repository recovery plan before history operations."],
        securityEvidenceIds: [secProjectIdentityEvidence.evidenceId, secManagementAccessEvidence.evidenceId],
      },
      researchMaturity: "CONCEPT",
      relationships: [{ kind: "OVERLAPS", targetId: "Ω-PLAN-R2-DESIGN-001" }],
      securityClosureSubstates: [
        {
          substateId: "PROJECT_IDENTIFIED",
          satisfied: true,
          epistemicState: "SUPPORTED",
          evidenceIds: [secProjectIdentityEvidence.evidenceId],
          rationale: "The repository-linked project identity is known without reproducing the credential.",
        },
        {
          substateId: "CORRECT_MANAGEMENT_ACCESS",
          satisfied: false,
          epistemicState: "INSUFFICIENT_EVIDENCE",
          evidenceIds: [secManagementAccessEvidence.evidenceId],
          rationale: "The current authenticated management session does not expose the repository-linked project.",
        },
        { substateId: "CREDENTIAL_RECORD_IDENTIFIED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "No authorized matching credential record is accessible." },
        { substateId: "VALIDITY_ESTABLISHED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "Credential validity cannot be inferred without management evidence." },
        { substateId: "USAGE_REVIEWED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "Usage and audit history are unavailable without correct management access." },
        { substateId: "REVOCATION_COMPLETED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "No revocation was attempted or completed." },
        { substateId: "REVOCATION_VERIFIED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "No authoritative revoked-state evidence exists." },
        { substateId: "DEPENDENCIES_ROTATED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "Dependent integration rotation awaits authoritative credential containment." },
        { substateId: "REMOTE_TIPS_REDACTED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "Remote-tip redaction is intentionally sequenced after credential invalidation." },
        { substateId: "HISTORY_POLICY_DECIDED", satisfied: false, epistemicState: "UNKNOWN", evidenceIds: [], rationale: "Shared-history sanitation remains a separate governance decision." },
      ],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-R2-DESIGN-001",
      originalSourceId: "Ω-R2-DESIGN-001",
      title: "Isolated Sandbox Write Authority Design",
      source: DIRECTIVE_003_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "SPECIFIED",
      maturityHistory: maturityHistory(["PROPOSED", "SPECIFIED"], r2DesignEvidence.evidenceId),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directive003Evidence, r2DesignEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-R2-DESIGN-SCOPE", "WRITE_SANDBOX is disposable, bounded, disjoint from the repository, and design-only.", "Executable design validator", "Every design invariant passes"),
        criterion("Ω-AC-R2-DESIGN-TX", "Mutation proposals fail closed on stale base hashes and incomplete rollback material.", "Transaction and rollback contract harness", "Every positive and adversarial contract case passes"),
        criterion("Ω-AC-R2-DESIGN-GATE", "Operational implementation remains gated by security, R1, rollback, negative-capability, and threat evidence.", "Eligibility decision", "Current state is INELIGIBLE with exact blockers"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-R2-DESIGN-AUTH", "The design exposes a write operation or treats repository writes as sandbox writes.", "Static API and negative-capability inspection", "Any operational write primitive or missing forbidden action"),
        criterion("Ω-FC-R2-DESIGN-ROLLBACK", "A transaction can validate without complete, equivalent rollback material.", "Adversarial contract fixtures", "Any incomplete rollback accepted"),
      ],
      dependencies: ["Ω-PLAN-SEC-003", "Ω-PLAN-EVAL-R1-001", "Ω-CAP-READ-REPOSITORY"],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/executor/r2Design.ts", status: "experimental" },
        { kind: "tool", ref: "scripts/omegaR2Design.test.ts", status: "active" },
      ],
      securityProfile: {
        threatModel: ["Sandbox escape", "stale-base overwrite", "incomplete rollback", "audit tampering", "authority confusion"],
        privilegeRequirements: ["No granted runtime authority; design validation only"],
        dataSensitivity: "INTERNAL",
        isolationRequirements: ["Future sandbox root must be disposable and disjoint from production repository."],
        attackSurface: ["Path normalization", "transaction validation", "rollback evidence", "capability-token authenticity", "audit ledger"],
        trustAssumptions: ["R1 remains verified", "current credential containment is unresolved", "hash chaining is not signing"],
        possibleMisuse: ["Treat design types as operational authorization", "inflate tamper evidence into signed evidence"],
        compromisePaths: ["Alias escape", "stale transaction", "forged future capability", "missing audit event"],
        blastRadius: "None from this design-only artifact; a future incorrect implementation could modify only its disposable sandbox if contracts hold.",
        containmentMechanisms: ["Disjoint roots", "strict bounds", "forbidden-action list", "base hashes", "eligibility gate"],
        rollbackMechanisms: ["Before-state material is mandatory", "rollback equivalence is a prerequisite", "no operational mutation is present"],
        securityEvidenceIds: [r2DesignEvidence.evidenceId],
      },
      researchMaturity: "EXPERIMENT_DESIGNED",
      hypothesis: {
        statement: "A design-only, fail-closed transaction boundary can prepare isolated mutation without weakening R1 trust properties.",
        supportCriterion: "All design invariants and adversarial transaction cases pass while operational eligibility remains blocked.",
        falsificationCriterion: "The design accepts repository mutation, stale base state, missing rollback, or unresolved security as eligible.",
        baseline: "R1 read-only executor at dc8126f with no mutation contract",
        competingExplanations: ["The contracts add bureaucracy without reducing future mutation risk", "Filesystem isolation must be enforced entirely below this layer"],
        measurementMethod: "Pure deterministic design, transaction, hash-chain, rollback, and eligibility tests",
        requiredPopulation: "Valid and adversarial roots, paths, bounds, hashes, rollback states, evidence chains, and gate states",
        computeBudget: "Single local CPU process; no filesystem mutation, model inference, or network",
        calibrationRequirement: "Specification verification must never be reported as implemented write capability",
      },
      relationships: [{ kind: "DERIVES_FROM", targetId: "Ω-PLAN-EVAL-R1-001" }],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-R2-A-SPEC-EVAL-001",
      originalSourceId: "Ω-R2-A-SPEC/EVAL-001",
      title: "Disposable Sandbox Provisioning Specification and Evaluator",
      source: DIRECTIVE_004_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "SPECIFIED",
      maturityHistory: maturityHistory(["PROPOSED", "SPECIFIED"], r2ASpecEvidence.evidenceId),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directive004Evidence, r2ASpecEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-R2-A-SPEC-NOAUTH", "The artifact specifies and evaluates R2-A without creating a sandbox or exposing a filesystem adapter.", "Static contract and deterministic evaluator", "Operational authority UNAVAILABLE; filesystem adapter NONE"),
        criterion("Ω-AC-R2-A-SPEC-BOUNDARY", "Future provisioning must prove canonical disjointness, stable target identity, bounded lifetime, and cleanup equivalence.", "Adversarial contract harness", "Every positive and negative contract case passes"),
        criterion("Ω-AC-R2-A-SPEC-GATE", "SEC-003 remains the controlling implementation gate.", "Eligibility decision", "Current decision INELIGIBLE with credential containment blocker"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-R2-A-SPEC-AUTH", "The specification exposes filesystem mutation or content writes.", "Static API inspection", "Any operational adapter or content mutation primitive"),
        criterion("Ω-FC-R2-A-SPEC-TOCTOU", "A changed target identity can satisfy the provisioning evidence contract.", "Adversarial identity fixture", "Any identity substitution accepted"),
        criterion("Ω-FC-R2-A-SPEC-READ", "WRITE_SANDBOX implicitly grants observation authority.", "Authority-composition fixture", "Any implied read scope"),
      ],
      dependencies: ["Ω-PLAN-SEC-003", "Ω-PLAN-R2-DESIGN-001", "Ω-PLAN-EVAL-R1-001", "Ω-CAP-READ-REPOSITORY"],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/executor/r2SandboxProvisioningSpec.ts", status: "experimental" },
        { kind: "tool", ref: "scripts/omegaR2ASpecEval.test.ts", status: "active" },
      ],
      securityProfile: {
        threatModel: ["Repository/sandbox overlap", "filesystem alias escape", "TOCTOU target substitution", "cleanup failure", "observation-authority expansion", "maturity inflation"],
        privilegeRequirements: ["No runtime privilege; pure specification and evaluator only"],
        dataSensitivity: "INTERNAL",
        isolationRequirements: ["No filesystem adapter", "No sandbox creation", "No content mutation", "No network or credentials"],
        attackSurface: ["Provisioning request validation", "identity evidence contract", "cleanup equivalence contract", "eligibility gate"],
        trustAssumptions: ["Operational implementation will be evaluated separately", "canonical identity requires host evidence", "SEC-003 remains unresolved"],
        possibleMisuse: ["Treating specification verification as capability verification", "assuming write authority implies read authority"],
        compromisePaths: ["Future adapter diverges from specification", "future target changes after validation"],
        blastRadius: "No operational blast radius; this artifact contains no filesystem adapter or granted authority.",
        containmentMechanisms: ["Operational authority is machine-labelled UNAVAILABLE", "content mutation is forbidden until R2-B", "current eligibility is INELIGIBLE"],
        rollbackMechanisms: ["Revert specification commit; no runtime state was mutated"],
        securityEvidenceIds: [r2ASpecEvidence.evidenceId],
      },
      researchMaturity: "EXPERIMENT_DESIGNED",
      hypothesis: {
        statement: "A separately evaluable R2-A contract can expose sandbox-provisioning failure modes before any write authority exists.",
        supportCriterion: "The contract rejects overlap, traversal, alias/identity substitution, expiry, resource, cleanup, and authority-expansion failures while remaining design-only.",
        falsificationCriterion: "The evaluator accepts any defined escape or requires operational authority to validate the specification.",
        baseline: "R2 design contracts at d2b7121 without a phase-specific provisioning evaluator",
        competingExplanations: ["The phase-specific contract adds no information beyond the generic R2 design", "Host-specific implementation evidence will invalidate important assumptions"],
        measurementMethod: "Pure deterministic specification/evaluator cases with explicit adversarial families and gate-state assertions",
        requiredPopulation: "Valid requests plus root redirection, aliases, duplicate identity, expiry, malformed paths, nesting, cleanup, contention, repository substitution, and TOCTOU cases",
        computeBudget: "Single local CPU process; no filesystem mutation, model inference, or network",
        calibrationRequirement: "Plan may be VERIFIED at SPECIFIED maturity while WRITE_SANDBOX remains UNVERIFIED and unavailable",
      },
      relationships: [{ kind: "DERIVES_FROM", targetId: "Ω-PLAN-R2-DESIGN-001" }],
    },
    {
      recordType: "PLAN",
      canonicalId: "Ω-PLAN-TS-RATCHET-001",
      originalSourceId: "Ω-TS-RATCHET-001",
      title: "Full-Project TypeScript Diagnostic Ratchet",
      source: DIRECTIVE_004_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        tsRatchetEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [directive004Evidence, tsRatchetEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-TS-RATCHET-BASE", "The accepted d2b7121 TypeScript debt is exactly reproducible.", "TypeScript 5.8.3 diagnostic capture", "Seven recognized baseline diagnostics"),
        criterion("Ω-AC-TS-RATCHET-NEW", "New TypeScript diagnostics fail the ratchet while resolved debt remains accepted.", "Multiset diagnostic comparison", "new=0; resolved count may increase"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-TS-RATCHET-BYPASS", "A diagnostic outside the accepted baseline does not fail the check.", "Synthetic and live ratchet fixtures", "Any new diagnostic accepted"),
        criterion("Ω-FC-TS-RATCHET-DRIFT", "The baseline loses its exact commit or compiler provenance.", "Baseline manifest validation", "Missing or changed provenance without explicit re-baseline"),
      ],
      dependencies: ["Ω-PLAN-REG-001A"],
      implementationMappings: [
        { kind: "tool", ref: "scripts/typescript/typecheck-ratchet.mjs", status: "active" },
        { kind: "repository", ref: "scripts/typescript/typecheck-baseline.json", status: "active" },
        { kind: "tool", ref: "scripts/omegaTsRatchet.test.mjs", status: "active" },
      ],
      securityProfile: {
        threatModel: ["Baseline expansion hides new debt", "path or line drift creates false regressions", "compiler failure yields no parseable evidence"],
        privilegeRequirements: ["Repository read and local TypeScript compiler execution only"],
        dataSensitivity: "INTERNAL",
        isolationRequirements: ["No network", "no repository mutation during check", "baseline changes require explicit review"],
        attackSurface: ["Diagnostic parser", "baseline manifest", "compiler invocation"],
        trustAssumptions: ["TypeScript 5.8.3 is installed from the locked workspace", "first-line diagnostic fingerprint sufficiently distinguishes current debt"],
        possibleMisuse: ["Silently adding new diagnostics to the baseline", "claiming the project is globally type-clean"],
        compromisePaths: ["Malformed compiler output", "unaudited baseline update"],
        blastRadius: "A false pass could permit new TypeScript debt; no runtime authority is granted.",
        containmentMechanisms: ["Exact commit and compiler version in manifest", "new diagnostics fail closed", "zero-diagnostic resolution is allowed without re-baselining"],
        rollbackMechanisms: ["Restore the prior immutable baseline manifest and checker"],
        securityEvidenceIds: [tsRatchetEvidence.evidenceId],
      },
      researchMaturity: "OPERATIONALIZED",
      hypothesis: {
        statement: "A stable diagnostic multiset can forbid new TypeScript debt without blocking work on seven pre-existing errors.",
        supportCriterion: "The live compiler reproduces the baseline exactly and synthetic new diagnostics fail while resolved diagnostics pass.",
        falsificationCriterion: "New debt is accepted, resolved debt fails, or unparseable compiler failure is treated as success.",
        baseline: "Seven freshly reproduced diagnostics at d2b7121716cb17d0b78e29b9a6510e8c122b901e",
        competingExplanations: ["Line-independent fingerprints may conflate distinct errors", "Fixing all seven errors immediately would be simpler"],
        measurementMethod: "TypeScript compiler execution plus normalized multiset comparison and synthetic adversarial cases",
        requiredPopulation: "Unchanged, reordered, duplicated, resolved, new, and unparseable diagnostic outcomes",
        computeBudget: "One local TypeScript compilation per ratchet execution",
        calibrationRequirement: "Passing means no new diagnostics, not a globally clean TypeScript project",
      },
      relationships: [{ kind: "OVERLAPS", targetId: "Ω-PLAN-R2-A-SPEC-EVAL-001" }],
    },
  ],
  capabilities: [
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-REGISTRY-INVARIANTS",
      originalSourceId: "Ω-REG-001A",
      title: "Machine-enforced institutional registry invariants",
      source: REPOSITORY_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        registryEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [registryEvidence],
      acceptanceCriteria: [criterion("Ω-AC-CAP-REG", "Registry invariant enforcement remains deterministic.", "Registry harness", "Zero failed invariant checks")],
      falsificationCriteria: [criterion("Ω-FC-CAP-REG", "An invalid object is accepted.", "Adversarial fixture", "Any acceptance")],
      dependencies: ["Ω-PLAN-REG-001A"],
      implementationMappings: [{ kind: "repository", ref: "src/lib/codelab/registry", status: "active" }],
      securityProfile: securityProfile([registryEvidence.evidenceId]),
      researchMaturity: "EXPERIMENT_RUN",
      relationships: [{ kind: "ENABLES", targetId: "Ω-CAP-READ-REPOSITORY" }],
      expectedEvidence: ["Deterministic invariant suite", "Serialization round trip", "Relationship queries"],
    },
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-READ-REPOSITORY",
      originalSourceId: "Ω-VS-001A",
      title: "Scoped attributable repository observation",
      source: DIRECTIVE_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        readOnlyExecutorEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [readOnlyExecutorEvidence, r1BaselineEvidence, r1PrivateEvaluationEvidence],
      acceptanceCriteria: [criterion("Ω-AC-CAP-READ", "Authorized reads succeed and forbidden reads fail closed.", "Executor adversarial harness", "All defined cases pass")],
      falsificationCriteria: [criterion("Ω-FC-CAP-READ", "Any request escapes scope or loses provenance.", "Executor adversarial harness", "Any escape or missing evidence")],
      dependencies: ["Ω-PLAN-VS-001A", "Ω-PLAN-EVAL-R1-001", "Ω-CAP-REGISTRY-INVARIANTS"],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/executor", status: "active" },
        { kind: "repository", ref: "git:7729cf3e3e6bdb9e8771dfcad6386ecc9fa55296", status: "historical" },
        { kind: "tool", ref: "scripts/evaluation/omegaR1PrivateEval.ts", status: "active" },
      ],
      securityProfile: securityProfile([readOnlyExecutorEvidence.evidenceId, r1PrivateEvaluationEvidence.evidenceId], "R1 scoped repository read only"),
      researchMaturity: "EXPERIMENT_RUN",
      relationships: [{ kind: "DEPENDS_ON", targetId: "Ω-CAP-REGISTRY-INVARIANTS" }],
      expectedEvidence: ["Authorization decisions", "Tool-action records", "Observation evidence", "Revocation tests", "Less-correlated private repository cases"],
      certificates: [
        capabilityCertificate("Ω-CERT-R1-A", "Authorized file observation", r1PrivateEvaluationEvidence.evidenceId, "2/2 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-B", "Directory observation", r1PrivateEvaluationEvidence.evidenceId, "1/1 held-out check passed"),
        capabilityCertificate("Ω-CERT-R1-C", "Metadata observation", r1PrivateEvaluationEvidence.evidenceId, "2/2 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-D", "Scope confinement", r1PrivateEvaluationEvidence.evidenceId, "6/6 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-E", "Canonical-path confinement", r1PrivateEvaluationEvidence.evidenceId, "1/1 real junction check passed"),
        capabilityCertificate("Ω-CERT-R1-F", "Revocation", r1PrivateEvaluationEvidence.evidenceId, "2/2 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-G", "Audit completeness", r1PrivateEvaluationEvidence.evidenceId, "3/3 independent-oracle checks passed"),
        capabilityCertificate("Ω-CERT-R1-H", "Epistemic failure handling", r1PrivateEvaluationEvidence.evidenceId, "4/4 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-I", "Resource-bound enforcement", r1PrivateEvaluationEvidence.evidenceId, "3/3 held-out checks passed"),
        capabilityCertificate("Ω-CERT-R1-J", "Host-filesystem edge cases", r1PrivateEvaluationEvidence.evidenceId, "7/7 checks passed with a real Windows junction"),
      ],
    },
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-WRITE-SANDBOX",
      originalSourceId: "Ω-R2-DESIGN-001",
      title: "Isolated sandbox write capability (design only)",
      source: DIRECTIVE_003_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "SPECIFIED",
      maturityHistory: maturityHistory(["PROPOSED", "SPECIFIED"], r2DesignEvidence.evidenceId),
      epistemicState: "INSUFFICIENT_EVIDENCE",
      verificationState: "UNVERIFIED",
      evidence: [r2DesignEvidence, r2ASpecEvidence],
      acceptanceCriteria: [
        criterion("Ω-AC-CAP-R2", "Future isolated writes preserve R1 boundaries and rollback exactly.", "Disposable filesystem demonstration and negative-capability regression", "R2-A through R2-G evidenced; A-prime equivalent to A after rollback"),
      ],
      falsificationCriteria: [
        criterion("Ω-FC-CAP-R2", "Any write escapes the sandbox, lacks provenance, or cannot roll back.", "Adversarial operational evaluation", "Any escape, omitted action, or rollback mismatch"),
      ],
      dependencies: ["Ω-PLAN-R2-DESIGN-001", "Ω-PLAN-R2-A-SPEC-EVAL-001", "Ω-PLAN-SEC-003", "Ω-CAP-READ-REPOSITORY"],
      implementationMappings: [
        { kind: "repository", ref: "src/lib/codelab/executor/r2Design.ts", status: "experimental" },
        { kind: "repository", ref: "src/lib/codelab/executor/r2SandboxProvisioningSpec.ts", status: "experimental" },
      ],
      securityProfile: {
        threatModel: ["Unimplemented capability is mistakenly represented as available.", "Future write escapes or weakens R1."],
        privilegeRequirements: ["No current runtime privilege"],
        dataSensitivity: "INTERNAL",
        isolationRequirements: ["Disposable root outside repository; no shell, network, credentials, package installation, or deployment."],
        attackSurface: ["Future sandbox adapter; currently only pure contract code"],
        trustAssumptions: ["Current contract tests do not prove future filesystem enforcement."],
        possibleMisuse: ["Invoking design validation as if it performed a write"],
        compromisePaths: ["Future implementation diverges from specification"],
        blastRadius: "No operational blast radius exists in this chunk because no write adapter is implemented.",
        containmentMechanisms: ["Capability remains INSUFFICIENT_EVIDENCE and UNVERIFIED", "eligibility gate is INELIGIBLE"],
        rollbackMechanisms: ["Specified only; not yet demonstrated"],
        securityEvidenceIds: [r2DesignEvidence.evidenceId, r2ASpecEvidence.evidenceId],
      },
      researchMaturity: "EXPERIMENT_DESIGNED",
      relationships: [{ kind: "DEPENDS_ON", targetId: "Ω-CAP-READ-REPOSITORY" }],
      expectedEvidence: ["Disposable sandbox demonstration", "Stable canonical target identity", "Negative-capability regression", "Rollback equivalence", "Tamper-evident session audit"],
    },
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-TS-ERROR-RATCHET",
      originalSourceId: "Ω-TS-RATCHET-001",
      title: "No-new-TypeScript-error enforcement",
      source: REPOSITORY_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        tsRatchetEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [tsRatchetEvidence],
      acceptanceCriteria: [criterion("Ω-AC-CAP-TS-RATCHET", "No diagnostic outside the accepted baseline is present.", "npm run typecheck:ratchet", "new=0")],
      falsificationCriteria: [criterion("Ω-FC-CAP-TS-RATCHET", "A new diagnostic exits successfully.", "Adversarial ratchet fixture", "Any false acceptance")],
      dependencies: ["Ω-PLAN-TS-RATCHET-001", "Ω-CAP-REGISTRY-INVARIANTS"],
      implementationMappings: [
        { kind: "tool", ref: "scripts/typescript/typecheck-ratchet.mjs", status: "active" },
        { kind: "repository", ref: "scripts/typescript/typecheck-baseline.json", status: "active" },
      ],
      securityProfile: securityProfile([tsRatchetEvidence.evidenceId], "Local deterministic compiler execution"),
      researchMaturity: "OPERATIONALIZED",
      relationships: [{ kind: "DEPENDS_ON", targetId: "Ω-CAP-REGISTRY-INVARIANTS" }],
      expectedEvidence: ["Exact baseline provenance", "Live TypeScript diagnostics", "Zero new diagnostics"],
    },
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-ORCHESTRA-CONTRACTS",
      originalSourceId: "ORCHESTRA-O0-O7A",
      title: "Deterministic ORCHESTRA protocol and orchestration contracts",
      source: REPOSITORY_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        orchestraEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [orchestraEvidence],
      acceptanceCriteria: [criterion("Ω-AC-CAP-ORCH", "Pinned deterministic contracts remain green.", "Omega aggregate test runner", "385 passed and zero failed")],
      falsificationCriteria: [criterion("Ω-FC-CAP-ORCH", "Any pinned contract fails.", "Omega aggregate test runner", "At least one failure")],
      dependencies: [],
      implementationMappings: [{ kind: "repository", ref: "src/lib/codelab", status: "active" }],
      securityProfile: securityProfile([orchestraEvidence.evidenceId]),
      researchMaturity: "EXPERIMENT_RUN",
      relationships: [],
      expectedEvidence: ["385 deterministic checks"],
    },
    {
      recordType: "CAPABILITY",
      canonicalId: "Ω-CAP-TRACKED-SECRET-DETECTION",
      originalSourceId: "Ω-SEC-001",
      title: "Tracked high-confidence secret detection",
      source: REPOSITORY_SOURCE,
      corpusStatus: "PARTIAL",
      losslessCertification: false,
      maturity: "VERIFIED",
      maturityHistory: maturityHistory(
        ["PROPOSED", "SPECIFIED", "PROTOTYPED", "IMPLEMENTED", "INTEGRATED", "VERIFIED"],
        secretEvidence.evidenceId,
      ),
      epistemicState: "SUPPORTED",
      verificationState: "VERIFIED",
      evidence: [secretEvidence],
      acceptanceCriteria: [criterion("Ω-AC-CAP-SECRET", "Tracked high-confidence secret patterns are rejected.", "Secret scanner", "Zero findings on accepted tree")],
      falsificationCriteria: [criterion("Ω-FC-CAP-SECRET", "A defined pattern bypasses the scanner.", "Secret scanner adversarial fixture", "Any bypass")],
      dependencies: [],
      implementationMappings: [{ kind: "tool", ref: "scripts/security/scan-secrets.mjs", status: "active" }],
      securityProfile: securityProfile([secretEvidence.evidenceId]),
      researchMaturity: "EXPERIMENT_RUN",
      relationships: [],
      expectedEvidence: ["Tracked-file scanner pass", "Adversarial scanner fixtures"],
    },
  ],
  regressions: [
    {
      capabilityId: "Ω-CAP-ORCHESTRA-CONTRACTS",
      expectedEvidence: ["385 deterministic checks"],
      previousResult: "385/385",
      currentResult: "385/385",
      change: "UNCHANGED",
      confidence: 1,
      previousEvidenceIds: [orchestraEvidence.evidenceId],
      currentEvidenceIds: [orchestraEvidence.evidenceId],
    },
    {
      capabilityId: "Ω-CAP-READ-REPOSITORY",
      expectedEvidence: ["Scoped repository observation harness", "Fresh private repository evaluation", "Real host alias confinement"],
      previousResult: "VERIFIED_R1_34_OF_34_AT_7729CF3",
      currentResult: "VERIFIED_R1_PRIVATE_31_OF_31",
      change: "IMPROVED",
      confidence: 1,
      previousEvidenceIds: [readOnlyExecutorEvidence.evidenceId, r1BaselineEvidence.evidenceId],
      currentEvidenceIds: [readOnlyExecutorEvidence.evidenceId, r1BaselineEvidence.evidenceId, r1PrivateEvaluationEvidence.evidenceId],
    },
    {
      capabilityId: "Ω-CAP-TRACKED-SECRET-DETECTION",
      expectedEvidence: ["Tracked-file scanner pass"],
      previousResult: "VERIFIED",
      currentResult: "VERIFIED",
      change: "UNCHANGED",
      confidence: 1,
      previousEvidenceIds: [secretEvidence.evidenceId],
      currentEvidenceIds: [secretEvidence.evidenceId],
    },
    {
      capabilityId: "Ω-CAP-WRITE-SANDBOX",
      expectedEvidence: ["Design contracts", "R2-A provisioning specification", "Disposable sandbox demonstration", "Rollback proof", "Preserved forbidden actions"],
      previousResult: "UNAVAILABLE",
      currentResult: "SPECIFIED_R2_A_NOT_IMPLEMENTED",
      change: "NEW",
      confidence: 1,
      previousEvidenceIds: [],
      currentEvidenceIds: [r2DesignEvidence.evidenceId, r2ASpecEvidence.evidenceId],
    },
    {
      capabilityId: "Ω-CAP-TS-ERROR-RATCHET",
      expectedEvidence: ["Exact baseline provenance", "Live TypeScript diagnostics", "Zero new diagnostics"],
      previousResult: "UNAVAILABLE",
      currentResult: "VERIFIED_BASELINE_7_CURRENT_7_NEW_0",
      change: "NEW",
      confidence: 1,
      previousEvidenceIds: [],
      currentEvidenceIds: [tsRatchetEvidence.evidenceId],
    },
  ],
} as const satisfies OmegaRegistry);
