import type { BiologicalSourceProvenance } from "./biologicalCircuitIR";
import flywireFullMapSource from "./flywireFullMapSource.json" with { type: "json" };

export const NYX_BIOLOGICAL_SOURCE_REGISTRY = Object.freeze({
  schemaVersion: 1,
  corpusStatus: "PARTIAL_JUST_IN_TIME_NOT_LOSSLESSLY_CERTIFIED",
  rawDataCommittedToProductRepository: false,
  sources: Object.freeze({
    flyvisFib25Fib19: Object.freeze({
      datasetId: "flyvis:fib25-fib19-v2.2",
      organism: "Drosophila melanogaster",
      nervousSystemRegion: "optic-lobe visual system",
      sourceRepository: "https://github.com/TuragaLab/flyvis",
      sourceCommit: "92b3845cc426dd309a1a0e1b3890156c42e14021",
      artifactPath: "flyvis/connectome/fib25-fib19_v2.2.json",
      artifactSha256: "6779065467F70CEF14E8F2F1005EFD4830FD29C00795C103756A6AF60607F825".toLowerCase(),
      licenseId: "MIT",
      evidenceClass: "E2",
      sourceConfidence: 0.95,
      retrievedAt: "2026-09-17T00:00:00.000Z",
    } satisfies BiologicalSourceProvenance),
    openWormWhiteWhole: Object.freeze({
      datasetId: "openworm:white-whole",
      organism: "Caenorhabditis elegans",
      nervousSystemRegion: "whole nervous system",
      sourceRepository: "https://github.com/openworm/ConnectomeToolbox",
      sourceCommit: "b9c0b4a7bc2ccf47d3ce7aac624e1b3e2ea86254",
      artifactPath: "cect/cache/White_whole.json",
      artifactSha256: "D9AE79E870D3FFEC97074272BC5B1E52C90C6E27143E982F14F31C6601B058F3".toLowerCase(),
      licenseId: "MIT",
      evidenceClass: "E2",
      sourceConfidence: 0.9,
      retrievedAt: "2026-09-17T00:00:00.000Z",
    } satisfies BiologicalSourceProvenance),
    flyWireWholeBrain: Object.freeze({
      datasetId: flywireFullMapSource.datasetId,
      organism: "Drosophila melanogaster",
      nervousSystemRegion: "adult whole-brain model input",
      sourceRepository: flywireFullMapSource.sourceRepository,
      sourceCommit: flywireFullMapSource.sourceCommit,
      officialMap: "https://codex.flywire.ai/",
      dataRelease: flywireFullMapSource.dataRelease,
      dataScope: flywireFullMapSource.scope,
      nodeCount: flywireFullMapSource.expectedNodes,
      connectionRows: flywireFullMapSource.expectedConnections,
      sourceArtifacts: flywireFullMapSource.files,
      accessState: "PINNED_MODEL_INPUT_REQUIRES_VERIFIED_LOCAL_CACHE",
      admissionState: "RESEARCH_RUNTIME_ONLY_NOT_COGNITIVELY_ADMITTED",
      redistribution: flywireFullMapSource.redistribution,
    }),
    micronsCortical: Object.freeze({
      datasetId: "microns:minnie65",
      organism: "Mus musculus",
      nervousSystemRegion: "visual cortex",
      sourceRepository: "https://github.com/cajal/microns-nda-access",
      sourceCommit: "8cd39b7bef38cd319759ae0cb38e3919f339c6b5",
      officialMap: "https://www.microns-explorer.org/cortical-mm3",
      dataRelease: "minnie65_public v1300",
      accessState: "ACCESS_INFRASTRUCTURE_CACHED_BULK_DATABASE_NOT_DOWNLOADED",
      admissionState: "DEFERRED_DUE_TO_SCALE_AND_NO_CURRENT_CAUSAL_NEED",
    }),
    wormWiringWholeAnimal: Object.freeze({
      datasetId: "wormwiring:whole-animal",
      organism: "Caenorhabditis elegans",
      nervousSystemRegion: "adult whole-animal nervous system",
      officialMap: "https://www.wormwiring.org/",
      accessState: "OFFICIAL_MAP_CONFIRMED_CONNECTIVITY_ARTIFACT_NOT_PINNED",
      admissionState: "DEFERRED_PENDING_VERSIONED_ARTIFACT_PROVENANCE_AND_LICENSE_REVIEW",
    }),
  }),
} as const);
