import { DIRECTIVE_008_PLAN_COVERAGE,INHERITED_OMEGA_CONSTRAINTS,type PlanCoverageRecord } from "../src/lib/codelab/registry/planCoverage";
import { evaluatePlanCoverageGate,measureArchitectureConsolidation,type AuthorityChangingCoverageSubmission } from "./evaluation/plan-coverage-gate/evaluator";
let passed=0;let failed=0;const failures:string[]=[];function assert(v:unknown,l:string):void{if(v)passed+=1;else{failed+=1;failures.push(l);console.error(`  x ${l}`)}}
function submission(changes:Partial<AuthorityChangingCoverageSubmission>={}):AuthorityChangingCoverageSubmission{return{schemaVersion:1,submissionId:"COVERAGE-R2-A",workstream:DIRECTIVE_008_PLAN_COVERAGE[0],authorityChangingCandidate:true,authorityImplications:[{from:"PROVISION_SANDBOX",relation:"DOES_NOT_IMPLY",to:"WRITE_SANDBOX_CONTENT",evidenceRefs:["evidence://authority-graph"]}],candidateEvidenceRefs:["evidence://candidate"],...changes}}
const eligible=evaluatePlanCoverageGate(submission());assert(eligible.decision==="ELIGIBLE_FOR_ASSURANCE_REVIEW","mapped authority-changing candidate may enter assurance review");assert(eligible.verificationStatus==="NOT_EVALUATED"&&eligible.capabilityAcceptance==="NOT_EVALUATED","plan alignment is neither verification nor acceptance");assert(!eligible.grantsAuthority,"plan coverage gate grants no authority");
assert(evaluatePlanCoverageGate(submission({authorityImplications:[]})).decision==="NOT_ELIGIBLE","unmapped authority implication blocks assurance entry");
const noDirect={...DIRECTIVE_008_PLAN_COVERAGE[0],directlyImplemented:[]} as PlanCoverageRecord;assert(evaluatePlanCoverageGate(submission({workstream:noDirect})).decision==="NOT_ELIGIBLE","major mechanism without direct plan mapping is ineligible");
const missingConstraint={...DIRECTIVE_008_PLAN_COVERAGE[0],inheritedConstraints:INHERITED_OMEGA_CONSTRAINTS.slice(1)} as PlanCoverageRecord;assert(evaluatePlanCoverageGate(submission({workstream:missingConstraint})).decision==="NOT_ELIGIBLE","missing inherited constraint blocks assurance entry");
assert(evaluatePlanCoverageGate(submission({candidateEvidenceRefs:[]})).decision==="INSUFFICIENT_EVIDENCE","mapped but unevidenced candidate remains insufficient");
const openConflict={...DIRECTIVE_008_PLAN_COVERAGE[0],conflicts:[{...DIRECTIVE_008_PLAN_COVERAGE[0].conflicts[0],disposition:"OPEN" as const}]} as PlanCoverageRecord;assert(evaluatePlanCoverageGate(submission({workstream:openConflict})).decision==="NOT_ELIGIBLE","open authority conflict blocks assurance entry");
const metrics=measureArchitectureConsolidation(DIRECTIVE_008_PLAN_COVERAGE,["registry","evidence-engine","planner"],["PLAN-REJECTED-X"]);assert(metrics.plansRepresented>0&&metrics.plansDeferred>0,"consolidation reports represented and deferred plan concepts");assert(metrics.capabilitiesCreated===6&&metrics.activeArchitecturalMechanisms===3,"consolidation distinguishes capabilities from active mechanisms");assert(metrics.plansRejectedExperimentally===1,"experimentally rejected plans remain measurable");
console.log(`Omega plan coverage gate tests - passed: ${passed}, failed: ${failed}`);if(failed){for(const f of failures)console.error(`  - ${f}`);process.exit(1)}
