import { readFileSync } from "node:fs";
import { evaluateR2ANegativeCapabilities, type NegativeCapabilityEvaluationInput } from "./evaluation/r2-negative-capability/evaluator";
let passed=0;let failed=0;const failures:string[]=[];function assert(v:unknown,l:string):void{if(v)passed+=1;else{failed+=1;failures.push(l);console.error(`  x ${l}`)}}
function input(changes:Partial<NegativeCapabilityEvaluationInput>={}):NegativeCapabilityEvaluationInput{return{schemaVersion:1,candidateCommit:"a".repeat(40),evaluatorVersion:"negative-cap-eval/1",baselineAllowed:["READ_REPOSITORY"],candidateAllowed:["READ_REPOSITORY","PROVISION_SANDBOX","TERMINATE_SANDBOX"],candidateUnavailable:["WRITE_SANDBOX","WRITE_SANDBOX_CONTENT"],candidateForbidden:["WRITE_REPOSITORY","SHELL","NETWORK","CREDENTIAL_ACCESS","PACKAGE_INSTALL","DEPLOYMENT"],baselineReadScopes:["repo://approved"],candidateReadScopes:["repo://approved"],persistentCapabilitiesAfterRevocation:[],evidenceRefs:["evidence://authority-delta"],...changes}}
const accepted=evaluateR2ANegativeCapabilities(input());assert(accepted.decision==="ACCEPT","exact R2-A authority delta passes dedicated evaluator");assert(accepted.addedAuthorities.join(",")==="PROVISION_SANDBOX,TERMINATE_SANDBOX","intended delta contains exactly provision and terminate");
for(const authority of ["WRITE_SANDBOX_CONTENT","WRITE_REPOSITORY","SHELL","NETWORK","CREDENTIAL_ACCESS","PACKAGE_INSTALL","DEPLOYMENT"]){const result=evaluateR2ANegativeCapabilities(input({candidateAllowed:[...input().candidateAllowed,authority]}));assert(result.decision==="REJECT",`${authority} exposure rejects rather than warns`)}
assert(evaluateR2ANegativeCapabilities(input({candidateReadScopes:["repo://approved","repo://unrelated"]})).decision==="REJECT","write authority cannot expand read scope");
assert(evaluateR2ANegativeCapabilities(input({persistentCapabilitiesAfterRevocation:["PROVISION_SANDBOX"]})).decision==="REJECT","persistent post-revocation capability rejects");
assert(evaluateR2ANegativeCapabilities(input({candidateUnavailable:["WRITE_SANDBOX_CONTENT"]})).decision==="REJECT","generic sandbox write must remain unavailable");
assert(evaluateR2ANegativeCapabilities(input({evidenceRefs:[]})).decision==="INSUFFICIENT_EVIDENCE","unevidenced delta cannot pass");assert(!accepted.certifiesOperationalCapability&&!accepted.grantsAuthority,"negative evaluator certifies no operational capability and grants no authority");
const evaluatorSource=readFileSync(new URL("./evaluation/r2-negative-capability/evaluator.ts",import.meta.url),"utf8");assert(!/r2CandidatePackage|authorityGraph|r2ProvisioningBlueprint/.test(evaluatorSource),"negative evaluator imports no candidate-package, authority-graph, or provisioning helpers");
console.log(`Omega R2-A negative capability tests - passed: ${passed}, failed: ${failed}`);if(failed){for(const f of failures)console.error(`  - ${f}`);process.exit(1)}
