import { OMEGA_R1_BASELINE_GENEALOGY,evaluateInstitutionalBaselineDiff,type DeltaClassification,type InstitutionalSnapshot } from "./evaluation/baseline-diff/evaluator";
import { OMEGA_R1_TRACEABLE_BASELINE_COMMIT,validateInstitutionalBaselineGenealogy } from "../src/lib/codelab/registry/baselineGenealogy";
import { OMEGA_R1_TRACEABLE_BASELINE } from "./omega/pre-r2-gate.mjs";
let passed=0;let failed=0;const failures:string[]=[];function assert(v:unknown,l:string):void{if(v)passed+=1;else{failed+=1;failures.push(l);console.error(`  x ${l}`)}}
function baseline():InstitutionalSnapshot{return{candidateCommit:OMEGA_R1_BASELINE_GENEALOGY[2].commit,capabilities:["READ_REPOSITORY"],authorities:["READ_REPOSITORY"],tests:["R1_PRIVATE","R1_EXECUTOR"],evidence:["E-R1"],securityInvariants:["NO_SCOPE_ESCAPE","NO_WRITE"],environmentAssumptions:["WINDOWS_SUPPORTED"],registryMappings:["CAP-R1"],evaluators:["R1_PRIVATE_EVAL"],evidenceRequirements:["E3_R1"]}}
function classification(deltaId:string,kind:DeltaClassification["classification"]="INTENTIONAL_SUPERSESSION"):DeltaClassification{return{deltaId,classification:kind,rationale:"Explicit reviewed delta",evidenceRefs:["evidence://delta"]}}
assert(OMEGA_R1_BASELINE_GENEALOGY.map((item)=>item.commit.slice(0,7)).join(",")==="7729cf3,734e402,6871720","three R1 baseline identities remain distinct and ordered");
assert(validateInstitutionalBaselineGenealogy().length===0,"registered R1 baseline genealogy is internally valid");
assert(OMEGA_R1_TRACEABLE_BASELINE===OMEGA_R1_TRACEABLE_BASELINE_COMMIT,"pre-R2 coordinator and registry use the same traceable baseline");
const unchanged=evaluateInstitutionalBaselineDiff(baseline(),baseline(),[]);assert(unchanged.decision==="ACCEPT"&&unchanged.deltas.length===0,"identical traceable baseline has explicit zero delta");
const added={...baseline(),candidateCommit:"a".repeat(40),capabilities:[...baseline().capabilities,"PROVISION_SANDBOX"],authorities:[...baseline().authorities,"PROVISION_SANDBOX"]};const addedIds=["CAPABILITIES:ADDED:PROVISION_SANDBOX","AUTHORITIES:ADDED:PROVISION_SANDBOX"];assert(evaluateInstitutionalBaselineDiff(baseline(),added,addedIds.map((id)=>classification(id))).decision==="ACCEPT","classified evidenced authority additions can enter further assurance");
const deletedTest={...baseline(),candidateCommit:"a".repeat(40),tests:["R1_EXECUTOR"]};const unknownTest=classification("TESTS:REMOVED:R1_PRIVATE","UNKNOWN");assert(evaluateInstitutionalBaselineDiff(baseline(),deletedTest,[unknownTest]).decision==="REJECT","unknown R1 test deletion rejects promotion");
const removedInvariant={...baseline(),candidateCommit:"a".repeat(40),securityInvariants:["NO_SCOPE_ESCAPE"]};assert(evaluateInstitutionalBaselineDiff(baseline(),removedInvariant,[classification("SECURITY_INVARIANTS:REMOVED:NO_WRITE","UNRELATED_CHANGE")]).decision==="REJECT","trust-boundary deletion cannot be called unrelated");
const unclassifiedEnv={...baseline(),candidateCommit:"a".repeat(40),environmentAssumptions:[...baseline().environmentAssumptions,"NODE_24"]};assert(evaluateInstitutionalBaselineDiff(baseline(),unclassifiedEnv,[]).decision==="INSUFFICIENT_EVIDENCE","unclassified environment delta remains explicit and insufficient");
const regression=evaluateInstitutionalBaselineDiff(baseline(),deletedTest,[classification("TESTS:REMOVED:R1_PRIVATE","REGRESSION")]);assert(regression.decision==="REJECT","classified regression rejects");assert(!unchanged.certifiesOperationalCapability&&!unchanged.grantsAuthority,"baseline diff grants and certifies no authority");
console.log(`Omega baseline diff assurance tests - passed: ${passed}, failed: ${failed}`);if(failed){for(const f of failures)console.error(`  - ${f}`);process.exit(1)}
