import { R2_A_AUDIT_OBLIGATIONS, computeAuditEventHash, reconstructR2AAudit, type AdmittedAuditEvent, type AuditEventType } from "./evaluation/audit-reconstruction/evaluator";
let passed=0;let failed=0;const failures:string[]=[];function assert(v:unknown,l:string):void{if(v)passed+=1;else{failed+=1;failures.push(l);console.error(`  x ${l}`)}}
const results:Record<AuditEventType,AdmittedAuditEvent["result"]>={REQUEST:"REQUESTED",AUTHORIZATION:"AUTHORIZED",PARENT_IDENTITY_VALIDATION:"SUCCEEDED",DISJOINTNESS_VALIDATION:"SUCCEEDED",PROVISION:"SUCCEEDED",CREATED_OBJECT_IDENTITY:"SUCCEEDED",TERMINATION_REQUEST:"REQUESTED",CLEANUP:"SUCCEEDED",POST_CLEANUP_OBSERVATION:"OBSERVED_CLEAN",REVOCATION:"REVOKED"};
function transcript(types:readonly AuditEventType[]=R2_A_AUDIT_OBLIGATIONS):AdmittedAuditEvent[]{let previous="GENESIS";return types.map((eventType,index)=>{const base:Omit<AdmittedAuditEvent,"eventHash">={schemaVersion:1,eventId:`EVENT-${index}-${eventType}`,eventType,requestId:"REQ-1",actorIdentity:eventType==="REQUEST"?"REQUESTOR-1":"EXECUTOR-1",authority:eventType==="AUTHORIZATION"?"R2_A_AUTHORIZATION":"PROVISION_SANDBOX",resourceIdentity:"sandbox-root://approved",objectIdentity:["REQUEST","PARENT_IDENTITY_VALIDATION","DISJOINTNESS_VALIDATION"].includes(eventType)?null:"sandbox://leaf-1",result:results[eventType],evidenceRef:`evidence://${eventType}`,previousHash:previous};const event={...base,eventHash:computeAuditEventHash(base)};previous=event.eventHash;return event})}
const complete=reconstructR2AAudit(transcript());assert(complete.decision==="COMPLETE","admitted mandatory transcript reconstructs completely");assert(complete.requestor==="REQUESTOR-1"&&complete.authorityAtAuthorization==="R2_A_AUTHORIZATION","requestor and authority reconstruct from admitted records");assert(complete.affectedObjectIdentity==="sandbox://leaf-1"&&complete.authorityAfterward==="REVOKED","affected identity and terminal revocation reconstruct");assert(complete.supportingEvidenceRefs.length===10,"every reconstructed semantic claim retains admitted evidence");
const removedAndRehashed=transcript(R2_A_AUDIT_OBLIGATIONS.filter((event)=>event!=="POST_CLEANUP_OBSERVATION"));const incomplete=reconstructR2AAudit(removedAndRehashed);assert(incomplete.decision==="INSUFFICIENT_EVIDENCE"&&incomplete.missingEvents.includes("POST_CLEANUP_OBSERVATION"),"internally consistent hash chain cannot hide missing semantic event");
const tampered=transcript();tampered[4]={...tampered[4],objectIdentity:"sandbox://different"};assert(reconstructR2AAudit(tampered).decision==="REJECT","hash-inconsistent admitted event rejects");
const denied=transcript();denied[1]={...denied[1],result:"DENIED"};let previous="GENESIS";const rehashed=denied.map((event)=>{const base={...event,previousHash:previous};delete (base as Partial<AdmittedAuditEvent>).eventHash;const next={...base,eventHash:computeAuditEventHash(base)} as AdmittedAuditEvent;previous=next.eventHash;return next});assert(reconstructR2AAudit(rehashed).decision==="REJECT","successful action after denied authorization rejects despite consistent hashes");
assert(complete.reconstructsFromAdmittedRecordsOnly&&!complete.grantsAuthority,"audit evaluator uses admitted records only and grants no authority");
console.log(`Omega audit reconstruction tests - passed: ${passed}, failed: ${failed}`);if(failed){for(const f of failures)console.error(`  - ${f}`);process.exit(1)}
