import { assessVerificationOptimization,collectVerificationTelemetry,decideEvidenceReuse,summarizeVerificationCost } from "./evaluation/verification-cost/telemetry";
let passed=0;let failed=0;const failures:string[]=[];function assert(v:unknown,l:string):void{if(v)passed+=1;else{failed+=1;failures.push(l);console.error(`  x ${l}`)}}
const records=collectVerificationTelemetry("a".repeat(40),[{suiteId:"SEC",status:"PASSED",durationMs:30,passedChecks:4,failedChecks:0,testIdentities:["a","b"],criticality:"CRITICAL_GATE"},{suiteId:"HELD",status:"PASSED",durationMs:70,passedChecks:3,failedChecks:0,semanticTestDefinitions:3,criticality:"HELD_OUT"}],{SEC:{importance:"SECURITY",resourceCategory:"FILESYSTEM"}});
assert(records[0].importance==="SECURITY"&&records[0].resourceCategory==="FILESYSTEM","telemetry records explicit security importance and resource category");assert(records[0].runtimeMs===30&&records[0].checkCount===4&&records[0].semanticTestCount===2,"telemetry captures runtime, checks, and semantic test count");assert(records.every((record)=>record.executionState==="FRESH_PASS"&&record.cacheReuseStatus==="NOT_REUSED"),"fresh execution is explicit");
const reused=decideEvidenceReuse({previousState:"FRESH_PASS",previousCandidateCommit:"a".repeat(40),currentCandidateCommit:"b".repeat(40),previousDependencies:{executor:"v1"},currentDependencies:{executor:"v1"},candidateChangeClass:"DOCUMENTATION_ONLY",candidateBindingPolicy:"SEMANTIC_EQUIVALENCE_ALLOWED"});assert(reused.state==="REUSED_VALID","dependency-proven documentation-only evidence reuse is explicit");
assert(decideEvidenceReuse({previousState:"FRESH_PASS",previousCandidateCommit:"a".repeat(40),currentCandidateCommit:"b".repeat(40),previousDependencies:{executor:"v1"},currentDependencies:{executor:"v2"},candidateChangeClass:"CODE",candidateBindingPolicy:"SEMANTIC_EQUIVALENCE_ALLOWED"}).state==="STALE","changed dependency makes evidence stale");assert(decideEvidenceReuse({previousState:"FRESH_PASS",previousCandidateCommit:"a".repeat(40),currentCandidateCommit:"b".repeat(40),previousDependencies:{},currentDependencies:{},candidateChangeClass:"DOCUMENTATION_ONLY",candidateBindingPolicy:"EXACT_COMMIT_REQUIRED"}).state==="STALE","exact candidate policy prevents cross-commit reuse");
assert(!assessVerificationOptimization({importance:"CRITICAL_GATE",action:"OMIT"}).allowed,"critical gate cannot be omitted for cost");assert(!assessVerificationOptimization({importance:"SECURITY",action:"OMIT"}).allowed,"security verification cannot be omitted for cost");assert(assessVerificationOptimization({importance:"SECURITY",action:"PARALLELIZE"}).allowed,"security verification may be parallelized without omission");assert(assessVerificationOptimization({importance:"CRITICAL_GATE",action:"CACHE",reuseState:"REUSED_VALID"}).allowed,"critical evidence may be reused only when dependency-proven valid");assert(!assessVerificationOptimization({importance:"REGRESSION",action:"REPLACE"}).allowed,"unevidenced replacement is forbidden");
const summary=summarizeVerificationCost(records);assert(summary.totalRuntimeMs===100&&summary.totalChecks===7&&summary.totalSemanticTests===5,"verification cost summary remains attributable");
console.log(`Omega verification cost tests - passed: ${passed}, failed: ${failed}`);if(failed){for(const f of failures)console.error(`  - ${f}`);process.exit(1)}
