
-- Enable pgcrypto extension if not already enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA extensions;

-- Recreate the function with proper extension reference
CREATE OR REPLACE FUNCTION public.generate_ministry_invite_code()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_caller_email text;
  v_raw_bytes bytea;
  v_plaintext text;
  v_hash text;
  v_last_generated timestamptz;
  v_chars text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  v_i int;
  v_byte int;
BEGIN
  -- Only super admin
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();
  IF v_caller_email != 'malekismail487@gmail.com' THEN
    RETURN json_build_object('success', false, 'error', 'Unauthorized');
  END IF;

  -- Check 15-minute cooldown from last generated code
  SELECT created_at INTO v_last_generated
  FROM ministry_access_codes
  WHERE expires_at IS NOT NULL
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_last_generated IS NOT NULL AND v_last_generated > now() - interval '15 minutes' THEN
    RETURN json_build_object('success', false, 'error', 'Cooldown active. Wait before generating another code.', 'cooldown_until', (v_last_generated + interval '15 minutes'));
  END IF;

  -- Generate 100-character alphanumeric code using pgcrypto
  v_raw_bytes := gen_random_bytes(100);
  v_plaintext := '';
  FOR v_i IN 0..99 LOOP
    v_byte := get_byte(v_raw_bytes, v_i);
    v_plaintext := v_plaintext || substr(v_chars, (v_byte % 62) + 1, 1);
  END LOOP;

  -- Hash it
  v_hash := encode(sha256(v_plaintext::bytea), 'hex');

  -- Deactivate all previous active codes
  UPDATE ministry_access_codes SET is_active = false WHERE is_active = true;

  -- Insert new hashed code with 15-min expiry
  INSERT INTO ministry_access_codes (code_hash, is_active, expires_at, description)
  VALUES (v_hash, true, now() + interval '15 minutes', 'Dynamic code generated by super admin');

  RETURN json_build_object('success', true, 'code', v_plaintext, 'expires_at', now() + interval '15 minutes');
END;
$function$;
