
-- 1. Add expires_at column to ministry_access_codes
ALTER TABLE public.ministry_access_codes ADD COLUMN IF NOT EXISTS expires_at timestamptz;

-- 2. Create generate_ministry_invite_code() RPC
CREATE OR REPLACE FUNCTION public.generate_ministry_invite_code()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_caller_email text;
  v_raw_bytes bytea;
  v_plaintext text;
  v_hash text;
  v_last_generated timestamptz;
  v_chars text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  v_i int;
  v_byte int;
BEGIN
  -- Only super admin
  SELECT email INTO v_caller_email FROM auth.users WHERE id = auth.uid();
  IF v_caller_email != 'malekismail487@gmail.com' THEN
    RETURN json_build_object('success', false, 'error', 'Unauthorized');
  END IF;

  -- Check 15-minute cooldown from last generated code
  SELECT created_at INTO v_last_generated
  FROM ministry_access_codes
  WHERE expires_at IS NOT NULL
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_last_generated IS NOT NULL AND v_last_generated > now() - interval '15 minutes' THEN
    RETURN json_build_object('success', false, 'error', 'Cooldown active. Wait before generating another code.', 'cooldown_until', (v_last_generated + interval '15 minutes'));
  END IF;

  -- Generate 100-character alphanumeric code
  v_raw_bytes := extensions.gen_random_bytes(100);
  v_plaintext := '';
  FOR v_i IN 0..99 LOOP
    v_byte := get_byte(v_raw_bytes, v_i);
    v_plaintext := v_plaintext || substr(v_chars, (v_byte % 62) + 1, 1);
  END LOOP;

  -- Hash it
  v_hash := encode(sha256(v_plaintext::bytea), 'hex');

  -- Deactivate all previous active codes
  UPDATE ministry_access_codes SET is_active = false WHERE is_active = true;

  -- Insert new hashed code with 15-min expiry
  INSERT INTO ministry_access_codes (code_hash, is_active, expires_at, description)
  VALUES (v_hash, true, now() + interval '15 minutes', 'Dynamic code generated by super admin');

  RETURN json_build_object('success', true, 'code', v_plaintext, 'expires_at', now() + interval '15 minutes');
END;
$function$;

-- 3. Update verify_ministry_code to check expires_at
CREATE OR REPLACE FUNCTION public.verify_ministry_code(p_code text, p_ip_address text DEFAULT NULL::text, p_user_agent text DEFAULT NULL::text, p_device_fingerprint text DEFAULT NULL::text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  code_valid boolean;
  v_session_token text;
  v_banned boolean;
BEGIN
  -- Check IP ban
  IF p_ip_address IS NOT NULL THEN
    SELECT EXISTS(
      SELECT 1 FROM ministry_ip_bans WHERE ip_address = p_ip_address
    ) INTO v_banned;
    IF v_banned THEN
      RETURN json_build_object('success', false, 'error', 'ACCESS DENIED', 'banned', true);
    END IF;
  END IF;

  -- Check device fingerprint ban
  IF p_device_fingerprint IS NOT NULL THEN
    SELECT EXISTS(
      SELECT 1 FROM ministry_ip_bans WHERE device_fingerprint = p_device_fingerprint
    ) INTO v_banned;
    IF v_banned THEN
      RETURN json_build_object('success', false, 'error', 'ACCESS DENIED', 'banned', true);
    END IF;
  END IF;

  -- Check code length
  IF length(p_code) != 100 THEN
    RETURN json_build_object('success', false, 'error', 'Invalid access code');
  END IF;

  -- Verify code (also check expiry: NULL means legacy/permanent, otherwise must be in future)
  SELECT EXISTS(
    SELECT 1 FROM ministry_access_codes
    WHERE code_hash = encode(sha256(p_code::bytea), 'hex')
    AND is_active = true
    AND (expires_at IS NULL OR expires_at > now())
  ) INTO code_valid;

  IF NOT code_valid THEN
    RETURN json_build_object('success', false, 'error', 'Invalid access code');
  END IF;

  -- Generate session token using pgcrypto
  v_session_token := encode(extensions.gen_random_bytes(64), 'hex');

  -- Create pending access request
  INSERT INTO ministry_access_requests (session_token, ip_address, user_agent, device_fingerprint, status)
  VALUES (v_session_token, p_ip_address, p_user_agent, p_device_fingerprint, 'pending');

  RETURN json_build_object('success', true, 'session_token', v_session_token, 'message', 'Awaiting super admin approval');
END;
$function$;
