// This file is automatically generated. Do not edit it directly.
const toggleSchoolStatus = async (school: School) => {
  const newStatus = school.status === 'active' ? 'suspended' : 'active';

  // Optimistically update state
  setSchools((prev) =>
    prev.map((s) => (s.id === school.id ? { ...s, status: newStatus } : s))
  );

  // Update Supabase in the background
  const { error } = await supabase
    .from('schools')
    .update({ status: newStatus })
    .eq('id', school.id);

  if (error) {
    // Revert state if error occurs
    setSchools((prev) =>
      prev.map((s) => (s.id === school.id ? { ...s, status: school.status } : s))
    );
    setError(error.message);
  }
};

const regenerateActivationCode = async (schoolId: string) => {
  const newCode = Math.random().toString(36).substring(2, 8).toUpperCase();

  // Optimistically update state
  setSchools((prev) =>
    prev.map((s) =>
      s.id === schoolId ? { ...s, activation_code: newCode, code_used: false } : s
    )
  );

  // Update Supabase in the background
  const { error } = await supabase
    .from('schools')
    .update({ activation_code: newCode, code_used: false })
    .eq('id', schoolId);

  if (error) {
    // Revert state if error occurs
    fetchSchools(); // fallback: refetch the data
    setError(error.message);
  }
};
