// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivzltzehosalijmkgzhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2emx0emVob3NhbGlqbWtnemhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MTM1NzAsImV4cCI6MjA4MjQ4OTU3MH0.bYt53y0eBB9wZFafhTcxTOgSYr8-F7xQzTlPJktCRYE";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
